### ISSUE TITLE
Getting this error in 2.8 for several different projects

### ISSUE THREAD

**Issue by montedre** [armory3d/armory#1033]
Any idea what would cause this error. In 2.8 version only. I have updated the SDK today.

Error: Cannot find module ‘./Tools/khamake/khamake.js’
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object. (E:\Armory28\Armory_05_win64_b28\Armory\armsdk\Kha\make.js:1:63)
at Module._compile (module.js:643:30)
at Object.Module._extensions…js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Does 'several different projects' mean that empty project still works? Or do all projects fail? I tried updating the Armory_05_win64_b28 from scratch and it seems to run.

**Comment by montedre** [comment]
Should have thought of that myself.  New download and update fixed the issue.
