### ISSUE TITLE
Custom shader with + blending

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1049]
Uncaught exception: Unable to get property 'raw' of undefined or null reference
			var vs = scontext.raw.vertex_structure;
			^
TypeError: Unable to get property 'raw' of undefined or null reference
   at render (krom.js:13892:4)
   at iron_RenderPath.prototype.submitDraw (krom.js:2697:4)
   at iron_RenderPath.prototype.drawMeshes (krom.js:2671:4)
   at armory_renderpath_RenderPathForward.drawMeshes (krom.js:1018:2)
   at armory_renderpath_RenderPathForward.commands (krom.js:1089:2)
   at iron_RenderPath.prototype.renderFrame (krom.js:2522:3)
   at renderFrame (krom.js:12330:3)
   at iron_Scene.prototype.renderFrame (krom.js:3610:4)
   at iron_App.render (krom.js:2307:2)
   at kha_System.render (krom.js:22877:3)

**Comment by trsh** [comment]
@BlackGoku36 

https://github.com/armory3d/armory_examples/tree/master/material_shaders

And check `Blending` for that custom Shader material

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/87e857a1875d4dcf8145f199164bae41b0eac517. For blending to work `blend` context should exist in `MyMaterial.json`.
