### ISSUE TITLE
KodeStudio does not start and fails to create project(Path issue probably)

### ISSUE THREAD

**Issue by mundusnine** [armory3d/armory#1077]
OS: Ubuntu 18.04
Armory 0.5b installed through the itch.io app using the stable SDK

Output when clicking KodeStudio button in Blender: 
```
Armory: Proxy objects synchronized
Read blend: /home/jsnadeau/Documents/projects/test-armory/scene.blend
Generating Krom project for Kode Studio

Armory v0.5 ($Id: 626ed79f35d8830a987f2794c95bac04c8934899 $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.79 (sub 0)
Traceback (most recent call last):
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/props_ui.py", line 610, in execute
    make.build('krom')
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/make.py", line 356, in build
    export_data(fp, sdk_path)
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/make.py", line 94, in export_data
    make_world.build()
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/make_world.py", line 17, in build
    build_node_tree(scene.world)
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/make_world.py", line 23, in build_node_tree
    rpdat = arm.utils.get_rp()
  File "/home/jsnadeau/.config/itch/apps/armory3d 2/Armory/armsdk//armory/blender/arm/utils.py", line 88, in get_rp
    return wrd.arm_rplist[wrd.arm_rplist_index]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1

location: <unknown location>:-1

```

Upon reading the output there seems to be a path issue where a `/` is added to a path already containing it. This is probably causing the issue.

**Comment by mundusnine** [comment]
Issue not present in Armory_06alpha0_linux64
