### ISSUE TITLE
Blender version on Linux UI not right

### ISSUE THREAD

**Issue by mundusnine** [armory3d/armory#1083]
Ubuntu 18.04 LTS
Installed through itch app and launched through itch app
Armory version-----> 06alpha0_linux64

![blender_linux_armory06a](https://user-images.githubusercontent.com/29337013/50725761-988b0380-10d0-11e9-9235-cbda039d4ba7.png)

Error message in console(seems Armory not related): 
```
Read prefs: /home/jsnadeau/.config/blender/2.80/config/userpref.blend
found bundled python: /home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/python
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
ERROR (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:6764 pyrna_srna_ExternalType: failed to find 'bpy_types' module
Traceback (most recent call last):
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy/__init__.py", line 48, in <module>
    from . import (
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy/utils/__init__.py", line 147, in <module>
    import bpy_types as _bpy_types  # keep for comparisons, never ever reload this.
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent
Error: dropbox with unknown operator: WM_OT_drop_blend_file
Traceback (most recent call last):
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy/__init__.py", line 48, in <module>
    from . import (
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy/utils/__init__.py", line 147, in <module>
    import bpy_types as _bpy_types  # keep for comparisons, never ever reload this.
  File "/home/jsnadeau/.config/itch/apps/armory3d/Armory/2.80/scripts/modules/bpy_types.py", line 987
    @classmethod
    ^
IndentationError: unexpected indent

location: <unknown location>:-1

location: <unknown location>:-1
``

**Comment by luboslenco** [comment]
Do builds from blender.org work? Any difference if you download manually from itch.io?

**Comment by luboslenco** [comment]
Thanks for getting this sorted!
