### ISSUE TITLE
totally broken after update

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1084]
I am getting this error when updating the latest version from itch.io
![image](https://user-images.githubusercontent.com/30187223/50727681-9fd8fe00-111e-11e9-8082-3993f7f11e98.png)

now on every .blend it gives this error: 
```
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\SK\Downloads\Armory_06alpha0_win64\Armory\armsdk\Kha\Kore\Tools\kraffiti\kraffiti.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Finished in 0.7132747173309326
Build failed, check console
```

**Comment by luboslenco** [comment]
Linky to https://github.com/armory3d/armory/issues/1081.
