### ISSUE TITLE
numpy not in Blenders default libraries but Armory uses it

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#1144]
The armory engine apparently uses numpy, but it is not included in the default Blender Python library. So it tries to load numpy from my system's Python and fails because I have Python 3.5 installed (and not 3.7 as Blender 2.8).
I get the same error when I type `import numpy` inside blenders interactive console in 2.8 but this is not a Blender bug as numpy isn't included in Blender by default. When I import numpy in a lower blender version, it works.

Is there a way to bundle the right numpy version with the addon?

Full error message:
```
location: C:\Users\User\Documents\Programme\Armory_06beta_win64\2.80\scripts\modules\bpy\ops.py:200
Error: Traceback (most recent call last):
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\Programme\Armory_06beta_win64\2.80\scripts\addons\armory.py", line 202, in execute
    import start
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\start.py", line 1, in <module>
    import arm.nodes_logic
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\arm\nodes_logic.py", lineTraceback (most recent call last):
  File "C:\Users\User\Documents\Programme\Armory_06beta_win64\2.80\scripts\addons\armory.py", line 292, in on_load_post
    bpy.ops.arm_addon.start()
  File "C:\Users\User\Documents\Programme\Armory_06beta_win64\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\Programme\Armory_06beta_win64\2.80\scripts\addons\armory.py", line 202, in execute
    import start
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\start.py", line 1, in <module>
    import arm.nodes_logic
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\arm\nodes_logic.py", line 6, in <module>
    from arm.logicnode import *
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\arm\logicnode\action_add_group.py", line 4, in <module>
    from arm.logicnode.arm_nodes import *
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\arm\logicnode\arm_nodes.py", line 4, in <module>
    import arm.utils
  File "C:/Users/User/Documents/Programme/Armory_06beta_win64/armsdk//armory/blender\arm\utils.py", line 10, in <module>
    import numpy as np
  File "C:\Program Files\Python35\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Python35\Lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\User\
Documents\Programme\Armory_06beta_win64\blender.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Armory_06beta_win64
Python 3.5.3
Numpy 1.16.1**

**Comment by luboslenco** [comment]
Hm is this still an issue? Did something change so it's no longer bundled? I tried running on a fresh Windows 10 machine recently and it seemed to work.

**Comment by MoritzBrueckner** [comment]
Oh, it works now! Maybe it was just the underlying Blender version that had this issue.
It's finally time to start learning Amory  :sunglasses:
