### ISSUE TITLE
Exception when mesh havn't Material

### ISSUE THREAD

**Issue by XQDD** [armory3d/armory#1161]
(Newest Git)
Add a material can fix it
```
Could not open file F:\code\blender\armory\hello\hello01_earth_moon_system/build_main/debug/krom/krom.bin.
iron.data.MaterialData:58: Material data "armdefault" not found!
Uncaught exception:
        this.name = raw.name;
        ^
TypeError: Unable to get property 'name' of undefined or null reference
   at iron_data_MaterialData (krom.js:7304:2)
   at Anonymous function (krom.js:7346:3)
   at iron_data_Data.getSceneRaw (krom.js:1744:3)
   at iron_data_MaterialData.parse (krom.js:7340:2)
   at iron_data_Data.getMaterial (krom.js:1598:2)
   at iron_Scene.prototype.createObject (krom.js:3266:6)
   at traverseObjects (krom.js:3087:7)
   at Anonymous function (krom.js:3093:6)
   at Anonymous function (krom.js:3433:7)
   at Anonymous function (krom.js:1992:4)

```

![image](https://user-images.githubusercontent.com/20871761/52694292-1b429080-2fa4-11e9-8ad8-fd63d42db60c.png)

**Comment by luboslenco** [comment]
Do you still get this error? If so can you paste the blend? Looks ok here so far.

**Comment by XQDD** [comment]
Yeah, fixed
