### ISSUE TITLE
Environment map with non 2:1 ratio throws error

### ISSUE THREAD

**Issue by XQDD** [armory3d/armory#1171]
```Prolog
Armory v0.6 ($Id: 988482e02afefe458b00e4dea75db2d01b76e49d $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 41)
CMFT info: Converting latlong image to cubemap.
CMFT info: Saving spherical harmonics coefficients to F:\code\blender\armory\hello\test2/build_test2/compiled/Assets/envmaps/hdr_irradiance.c
CMFT info: Done.
CMFT info: Image is not cubemap(6 faces), cubecross(ratio 3:4 or 4:3), latlong(ratio 2:1), hstrip(ratio 6:1), vstrip(ration 1:6)
CMFT info: Conversion failed. Exiting...
Traceback (most recent call last):
  File "D:/software/Armory/armsdk//armory/blender\arm\props_ui.py", line 501, in execute
    make.play()
  File "D:/software/Armory/armsdk//armory/blender\arm\make.py", line 468, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:/software/Armory/armsdk//armory/blender\arm\make.py", line 352, in build
    export_data(fp, sdk_path)
  File "D:/software/Armory/armsdk//armory/blender\arm\make.py", line 94, in export_data
    make_world.build()
  File "D:/software/Armory/armsdk//armory/blender\arm\make_world.py", line 17, in build
    build_node_tree(scene.world)
  File "D:/software/Armory/armsdk//armory/blender\arm\make_world.py", line 30, in build_node_tree
    parse_world_output(world, output_node)
  File "D:/software/Armory/armsdk//armory/blender\arm\make_world.py", line 64, in parse_world_output
    parse_surface(world, surface_node)
  File "D:/software/Armory/armsdk//armory/blender\arm\make_world.py", line 84, in parse_surface
    parse_color(world, color_node)
  File "D:/software/Armory/armsdk//armory/blender\arm\make_world.py", line 157, in parse_color
    mip_count = write_probes.write_probes(filepath, disable_hdr, mip_count, arm_radiance=rpdat.arm_radiance)
  File "D:/software/Armory/armsdk//armory/blender\arm\write_probes.py", line 179, in write_probes
    mip_name + '.hdr')
FileNotFoundError: [WinError 2] ???????????????????????????????€?: 'F:\\code\\blender\\armory\\hello\\test2/build_test2/compiled/Assets/envmaps/hdr_radiance_0_512x256.hdr' -> 'F:\\code\\blender\\armory\\hello\\test2/build_test2/compiled/Assets/envmaps/hdr_radiance_0.hdr'

location: <unknown location>:-1

location: <unknown location>:-1

```
![image](https://user-images.githubusercontent.com/20871761/52857862-69ea5900-3163-11e9-8a83-3fc490372b82.png)

[test2.zip](https://xqddin.cn/test2.zip)

**Comment by BlackGoku36** [comment]
I think it happens because you are using `.png` format instead of `.hdr` format

**Comment by XQDD** [comment]
@BlackGoku36 I don't know whether to must need an hdr format because it works in both cycle and Eevee.

**Comment by trsh** [comment]
If it's only HDR, the Environment node file select dialog should be restricted to .hdr format. For now it's just confusing. Nothing says, that u can't use png's orsmth.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/e1cc3087092d83d1d9ce880e37ae65f8d65fa709.
