### ISSUE TITLE
Not able to add any logic nodes

### ISSUE THREAD

**Issue by thefixerofworlds** [armory3d/armory#1187]
```
Traceback (most recent call last):
  File "../armory/armsdk//armory/blender/arm/nodes_logic.py", line 97, in execute
    bpy.ops.node.add_node(type=self.item, use_transform=True)
  File "../armory/2.80/scripts/modules/bpy/ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.node.add_node.poll() failed, context is incorrect
```
Operating system Ubuntu 16.x, SDK updated, armory 0.6

**Comment by thefixerofworlds** [comment]
Nm
