### ISSUE TITLE
Kraffiti crash due to HDR environnement map

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#129]
Well, it crashes, plus is composition nodes supported in build 7 ?
http://pasteall.org/blend/index.php?id=45427

---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Heyho,

Unable to reproduce the crash - please paste your full command line output when building the project, might spot something useful. Also check on your antivirus, there are reports of avast blocking kraffiti.exe file.

![0890ae4e-dc1e-11e6-882a-a92e6c13a8e0](https://cloud.githubusercontent.com/assets/3685704/22625967/b2d3ea68-eba2-11e6-9c32-73b5481b7589.png)

**Comment by MagicalPaladin** [comment]
I've got Avira, here is the full log :
Armory v17.01.1
Traceback (most recent call last):
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\props_ui.py", line 491, in execute
    make.play_project(True)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make.py", line 348, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make.py", line 268, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make.py", line 80, in export_data
    world_outputs = make_world.build_node_trees(active_worlds)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make_world.py", line 25, in build_node_trees
    output = build_node_tree(world)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make_world.py", line 45, in build_node_tree
    parse_world_output(world, output_node, context)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make_world.py", line 120, in parse_world_output
    parse_surface(world, surface_node, context)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make_world.py", line 141, in parse_surface
    parse_color(world, color_node, context, envmap_strength_const)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\make_world.py", line 220, in parse_color
    mip_count = write_probes.write_probes(filepath, disable_hdr, mip_count, generate_radiance=wrd.generate_radiance)
  File "D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//armory/blender\write_probes.py", line 71, in write_probes
    'height=' + str(target_h)])
  File "D:\Documents Thoom\Documents\Downloads\Arm_p07_win64\Armory\2.78\python\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "D:\Documents Thoom\Documents\Downloads\Arm_p07_win64\Armory\2.78\python\lib\subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:/Documents Thoom/Documents/Downloads/Arm_p07_win64/Armory/armsdk//win32/Kha/Kore/Tools/kraffiti/kraffiti.exe', 'from=E:\\models+pepakura\\NPR\\ ressources/build/compiled/Assets/unpacked/clear_1_7.5.hdr', 'to=build/compiled/Assets/envmaps/clear_1_7.5_radiance.hdr', 'format=hdr', 'width=2048', 'height=1024']' returned non-zero exit status 3221225477

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Maybe it's this path `E:\models+pepakura`? Try to get rid of '+'(or any special characters in path). If that's an issue I will add warning for that.

**Comment by MagicalPaladin** [comment]
Same error

**Comment by luboslenco** [comment]
Sorry, will need more data to fix this, for some reason your blend file works fine here. Do all projects crash? Does it crash using jpg format? Did you check if the file is not blocked by antivirus?

![capture](https://cloud.githubusercontent.com/assets/3685704/22626664/54116760-ebb3-11e6-8e45-d6f832e2978d.JPG)

**Comment by MagicalPaladin** [comment]
That's really weird, most of my project crash (scene 3 is totally bugged). Defaut sky texture work but not any Environnement texture, jpg or HDR.

**Comment by Nopotato** [comment]
I also get kraffiti crash after adding a HDR texture. error message goes off the screen and I don't know how to copy the text from them.
![screenshot 2017-07-12 21 49 54](https://user-images.githubusercontent.com/3679297/28137053-2bb4c270-674c-11e7-8b0b-082eb5e17943.png)

**Comment by luboslenco** [comment]
Can you share the .hdr file? Need to fix this, but for some reason I am unable to reproduce so far.

**Comment by Nopotato** [comment]
HDRI 360 degree field italy from openfootage.net
https://www.openfootage.net/hdri-360-degree-field-italy/

**Comment by luboslenco** [comment]
Continuing to battle this at https://github.com/armory3d/armory/issues/129.
