### ISSUE TITLE
cannot build / publish to Krom Windows in Linux

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#1305]
### SHORT DESCRIPTION:
Build/Publish of the default cube scene fails with target: Krom (Windows) and all graphics API in Linux.

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Armory: v2019.5 ($Id: 1669fe81d52283ecb6ecd4c6c8f0c8ca6770fadb $)
Operating system: Ubuntu 18.04.2

### LOGS:

<details><summary>Build with auto / DX11 / DX12</summary>
<p>

```
Armory v2019.5 ($Id: 1669fe81d52283ecb6ecd4c6c8f0c8ca6770fadb $)
OS: linux, Target: krom-windows, GAPI: direct3d11, Blender: 2.80 (sub 44)
Exporting Scene
Scene exported in 0.004908561706542969
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//nodejs/node-linux64', '/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//Kha/make', 'krom', '-g', 'direct3d11', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_test/debug', '--nohaxe', '--noproject']
Using project from /home/user/Documents/Armory projects/self/latest_commit/test2/test.2
Using Kha from /home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 4 (Scene.arm).
Exporting asset 2 of 4 (World_irradiance.arm).
Exporting asset 3 of 4 (mesh_Cube.arm).
Exporting asset 4 of 4 (mesh_Suzanne.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Compiling shader 1 of 19 (Material_mesh.frag.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl).
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl).
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl) failed:
Shader compiler error.
(node:25821) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Shader compiler error.
(node:25821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 19 (Material_mesh.frag.glsl) failed:
Shader compiler error.
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl) failed:
Shader compiler error.
Build failed, check console
```

</p>
</details>

<details><summary>Publish Auto/DX11/DX12</summary>
<p>

```
Armory v2019.5 ($Id: 1669fe81d52283ecb6ecd4c6c8f0c8ca6770fadb $)
OS: linux, Target: krom-windows, GAPI: direct3d11, Blender: 2.80 (sub 44)
Exporting Scene
Exporting mesh Cube
Scene exported in 0.0055713653564453125
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//nodejs/node-linux64', '/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//Kha/make', 'krom', '-g', 'direct3d11', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_test']
Using project from /home/user/Documents/Armory projects/self/latest_commit/test2/test.2
Info: Publishing project, check console for details.

Using Kha from /home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 3 (Scene.arm).
Exporting asset 2 of 3 (World_irradiance.arm).
Exporting asset 3 of 3 (mesh_Cube.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Compiling shader 1 of 19 (Material_mesh.frag.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl).
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl).
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl) failed:
Shader compiler error.
(node:27070) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Shader compiler error.
(node:27070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 19 (Material_mesh.frag.glsl) failed:
Shader compiler error.
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl) failed:
Shader compiler error.
Finished in 0.49828004837036133
Build failed, check console
```

</p>
</details>

<details><summary>Publish openGL</summary>
<p>

```
Armory v2019.5 ($Id: 1669fe81d52283ecb6ecd4c6c8f0c8ca6770fadb $)
OS: linux, Target: krom-windows, GAPI: opengl, Blender: 2.80 (sub 44)
Exporting Scene
Exporting mesh Cube
Scene exported in 0.0054852962493896484
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//nodejs/node-linux64', '/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_test']
Using project from /home/user/Documents/Armory projects/self/latest_commit/test2/test.2
Info: Publishing project, check console for details.

Using Kha from /home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 3 (Scene.arm).
Exporting asset 2 of 3 (World_irradiance.arm).
Exporting asset 3 of 3 (mesh_Cube.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Compiling shader 1 of 19 (Material_mesh.frag.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl).
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl).
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl).
Compiling shader 5 of 19 (blur_edge_pass.frag.glsl).
Compiling shader 6 of 19 (compositor_pass.frag.glsl).
Compiling shader 7 of 19 (compositor_pass.vert.glsl).
Compiling shader 8 of 19 (deferred_light.frag.glsl).
Compiling shader 9 of 19 (pass.vert.glsl).
Compiling shader 10 of 19 (pass_viewray.vert.glsl).
Compiling shader 11 of 19 (smaa_blend_weight.frag.glsl).
Compiling shader 12 of 19 (smaa_blend_weight.vert.glsl).
Compiling shader 13 of 19 (smaa_edge_detect.frag.glsl).
Compiling shader 14 of 19 (smaa_edge_detect.vert.glsl).
Compiling shader 15 of 19 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 16 of 19 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 17 of 19 (ssao_pass.frag.glsl).
Compiling shader 18 of 19 (world_pass.frag.glsl).
Compiling shader 19 of 19 (world_pass.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 3.226332902908325
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 32, in fn
    done()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 402, in build_done
    build_success()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 577, in build_success
    proc = subprocess.Popen(args)
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'test.exe': 'test.exe'
```

</p>
</details>

<details><summary>Publish Vulkan</summary>
<p>

```
Armory v2019.5 ($Id: 1669fe81d52283ecb6ecd4c6c8f0c8ca6770fadb $)
OS: linux, Target: krom-windows, GAPI: vulkan, Blender: 2.80 (sub 44)
Exporting Scene
Exporting mesh Cube
Scene exported in 0.00617218017578125
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//nodejs/node-linux64', '/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//Kha/make', 'krom', '-g', 'vulkan', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_test']
Using project from /home/user/Documents/Armory projects/self/latest_commit/test2/test.2
Info: Publishing project, check console for details.

Using Kha from /home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 3 (Scene.arm).
Exporting asset 2 of 3 (World_irradiance.arm).
Exporting asset 3 of 3 (mesh_Cube.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Compiling shader 1 of 19 (Material_mesh.frag.glsl).
Compiling shader 2 of 19 (Material_mesh.vert.glsl).
Compiling shader 3 of 19 (Material_shadowmap.frag.glsl).
Compiling shader 4 of 19 (Material_shadowmap.vert.glsl).
Compiling shader 5 of 19 (blur_edge_pass.frag.glsl).
Compiling shader 6 of 19 (compositor_pass.frag.glsl).
Compiling shader 7 of 19 (compositor_pass.vert.glsl).
Compiling shader 8 of 19 (deferred_light.frag.glsl).
Compiling shader 9 of 19 (pass.vert.glsl).
Compiling shader 10 of 19 (pass_viewray.vert.glsl).
Compiling shader 11 of 19 (smaa_blend_weight.frag.glsl).
Compiling shader 12 of 19 (smaa_blend_weight.vert.glsl).
Compiling shader 13 of 19 (smaa_edge_detect.frag.glsl).
Compiling shader 14 of 19 (smaa_edge_detect.vert.glsl).
Compiling shader 15 of 19 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 16 of 19 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 17 of 19 (ssao_pass.frag.glsl).
Compiling shader 18 of 19 (world_pass.frag.glsl).
Compiling shader 19 of 19 (world_pass.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 3.1978330612182617
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 32, in fn
    done()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 402, in build_done
    build_success()
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//armory/blender/arm/make.py", line 549, in build_success
    shutil.copy(krom_location, files_path + '/Krom.exe')
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/2.80/python/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Downloads/Armory_06_linux64/Armory_latest_commit/armsdk//Krom/Krom_vulkan.exe'
```

</p>
</details>

**Comment by tong** [comment]
Still doesn't work for me.

**Comment by tong** [comment]
When publishing to windows/opengl i get:
`FileNotFoundError: [Errno 2] No such file or directory: '/armory/armsdk/Krom/Krom_opengl.exe'`

Which makes me wonder how publishing to a specific gapi can work at all if it requires to have an extra Krom_*gapi*.exe which is not distributed with armsdk.
