### ISSUE TITLE
Build 7 Live Patching problem

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#131]
Hello,
with live patching enabled when i try to touch material nodes the Node view switch automatically to 3D view and Live patching does not work ( in Build 6 similar problem but without automatic switch of the views )

My system : OS X® 10.11.6
How to reproduce:
default cube-> Play in Viewport-> try to change material nodes

If useful i can prepare a video
Console report:
```
Armory v17.01.1
Exporting mesh Cube
Scene built in 0.00451207160949707
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CompoTonemap.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CompoTonemap.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CompoTonemap.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Image brdf.png
Image noise8.png
Image smaa_area.png
Image smaa_search.png
Uniform envmapStrength not found.

Armory v17.01.1
Traceback (most recent call last):
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/handlers.py", line 67, in on_scene_update_post
    make.play_project(in_viewport=True)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/make.py", line 348, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/make.py", line 268, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/make.py", line 95, in export_data
    exporter.execute(bpy.context, asset_path)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/exporter.py", line 2412, in execute
    self.export_materials()
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/exporter.py", line 2210, in export_materials
    sd, is_transluc = make_material.parse(material, o, self.materialToObjectDict, ArmoryExporter.renderpath_id)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/material/make.py", line 44, in parse
    rpasses = mat_utils.get_rpasses(material)
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/material/mat_utils.py", line 29, in get_rpasses
    elif is_transluc(material):
  File "/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app//armsdk//armory/blender/material/mat_utils.py", line 45, in is_transluc
    surface_node = output_node.inputs[0].links[0].from_node
IndexError: tuple index out of range

Armory v17.01.1
Scene built in 0.0032880306243896484

```

**Comment by AndreaMonzini** [comment]
Hello, 
just to report that i have the same issue with Build 8.

**Comment by luboslenco** [comment]
Materials should now be properly recompiled and patched.
