### ISSUE TITLE
'CyclesRenderSettings' object has no attribute 'film_transparent'

### ISSUE THREAD

**Issue by ghaspias** [armory3d/armory#1336]
Tried to install the armory add-on from Armory_06_win64 in the official Blender 2.80 release, following the instructions from https://armory3d.org/manual/#/getting_started/setup. Although the add-on is activated, when trying to run the project from within Blender results in an error.
Below is the message logged to the console:

Armory v0.6 ($Id: 988482e02afefe458b00e4dea75db2d01b76e49d $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 75)
Traceback (most recent call last):
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\props_ui.py", line 501, in execute
    make.play()
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\make.py", line 468, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\make.py", line 352, in build
    export_data(fp, sdk_path)
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\make.py", line 94, in export_data
    make_world.build()
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\make_world.py", line 17, in build
    build_node_tree(scene.world)
  File "C:\Users\migue\Downloads\Armory\armsdk//armory/blender\arm\make_world.py", line 50, in build_node_tree
    if bpy.context.scene != None and bpy.context.scene.cycles != None and bpy.context.scene.cycles.film_transparent:
AttributeError: 'CyclesRenderSettings' object has no attribute 'film_transparent'

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Hi, you will need to use the latest `ArmorySDK-2019-08` release because Blender API changed since the 0.6 was released.
