### ISSUE TITLE
Python import error on start

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#151]
On Ubuntu 16.10, Armory preview08b linux64

This is strange, all of a sudden I'm getting this error when I start blender from armory directory:

```bash
Traceback (most recent call last):
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons/armory.py", line 235, in execute
    import start
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/start.py", line 1, in <module>
    import make
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/make.py", line 18, in <module>
    from exporter import ArmoryExporter
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/exporter.py", line 24, in <module>
    import material.make as make_material
ImportError: No module named 'material.make'

location: /home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py:187

location: /home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py:187
Error: Traceback (most recent call last):
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons/armory.py", line 235, in execute
    import start
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/start.py", line 1, in <module>
    import make
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/make.py", line 18, in <module>
    from exporter import ArmoryExporter
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/exporter.py", line 24, in <module>
    import material.make as make_material
ImportError: No module named 'material.make'

location: /home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py:187

Traceback (most recent call last):
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons/armory.py", line 123, in on_scene_update_post
    bpy.ops.arm_addon.start('EXEC_DEFAULT')
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py", line 187, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons/armory.py", line 235, in execute
    import start
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/start.py", line 1, in <module>
    import make
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/make.py", line 18, in <module>
    from exporter import ArmoryExporter
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/exporter.py", line 24, in <module>
    import material.make as make_material
ImportError: No module named 'material.make'

location: /home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py:187
```

Could it be related to the double slash? Have no idea.

```python
>>> import sys
>>> sys.path #gives
['/home/razvan/.config/blender/2.78/scripts/addons/blender-osm',
'/home/razvan/.config/blender/2.78/scripts/addons',
'/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons',
'/home/razvan/Itch/Armory3D/Armory/2.78/scripts/startup',
'/home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules',
'/home/razvan/Itch/Armory3D/Armory/2.78/python/lib/python35.zip',
'/home/razvan/Itch/Armory3D/Armory/2.78/python/lib/python3.5',
'/home/razvan/Itch/Armory3D/Armory/2.78/python/lib/python3.5/plat-x86_64-linux-gnu',
'/home/razvan/Itch/Armory3D/Armory/2.78/python/lib/python3.5/lib-dynload',
'/home/razvan/.local/lib/python3.5/site-packages',
'/home/razvan/Itch/Armory3D/Armory/2.78/python/lib/python3.5/dist-packages',
'/home/razvan/Itch/Armory3D/Armory/2.78/scripts/freestyle/modules',
'/home/razvan/Itch/Armory3D/Armory/2.78/scripts/addons/modules',
'/home/razvan/.config/blender/2.78/scripts/addons/modules',
'/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/']
```

**Comment by razvanc-r** [comment]
Oh, I discovered why. Seems that `blender-osm` also has a folder/module called `material` and Armory doesn't like this too much. Any ideas on a workaround? I need `blender-osm` to make peace with Aromory :)

**Comment by luboslenco** [comment]
Fixed by moving Armory py sources to separate package to prevent conflicts like this. Should work out of the box with `blender-osm` in next build (Monday) :)
