### ISSUE TITLE
Game won't start if object is linked to two other scenes

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1564]
Armory v2020.2 ($Id: 29eed7c87a5edde6fb0a5ff1814d57116f09cb46 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.81 (sub 16)

Hi,

the game won't start if an object is linked to at least two other scenes. To reproduce: start a new blend file, create two new scenes, select the default cube and link it to the other two scenes (Ctrl-L --> Objects to Scene --> select the other scene, repeat for the 2nd scene).

The following error occurs:
```
Traceback (most recent call last):
  File "D:\Portables\armorySDK2002//armory/blender\arm\props_ui.py", line 457, in execute
    make.play()
  File "D:\Portables\armorySDK2002//armory/blender\arm\make.py", line 472, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\Portables\armorySDK2002//armory/blender\arm\make.py", line 356, in build
    export_data(fp, sdk_path)
  File "D:\Portables\armorySDK2002//armory/blender\arm\make.py", line 112, in export_data
    if o.type == "MESH" or o.type == "EMPTY":  export_coll.objects.link(o)
RuntimeError: Error: Object 'Cube' already in collection 'export_coll'
```

File to reproduce the error:
[LinkedScene.zip](https://github.com/armory3d/armory/files/4172826/LinkedScene.zip)

**Comment by blackno666** [comment]
Probably due to  N8n5h's committed on 1 Dec 2019 on make.py

I guess when adding objects to the zoo collection it should be checked if the object's alread in it; like so:

```
for scene in bpy.data.scenes:
    if scene == bpy.context.scene: continue
    for o in scene.collection.all_objects:
        if o.type == "MESH" or o.type == "EMPTY":
            if o.name not in  export_coll.all_objects.keys():  # only add if objec'ts not already in collection
                export_coll.objects.link(o
```
