### ISSUE TITLE
Android C publishing not working when using External Lbs

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1580]
Android C publishing is not working when using an External Libraries. When using one this error shows up:
```
Exporting mesh Icosphere
Scene exported in 0.17955708503723145
Exported modules: ['audio', 'physics', 'ui']
Shader flags: ['_Irr', '_EnvSky', '_EnvStr', '_LDR', '_ShadowMap', '_Sun', '_Probes']
Running:  ['C:/Users/SK/Desktop/Armory/Armory/armsdk//nodejs/node.exe', 'C:/Users/SK/Desktop/Armory/Armory/armsdk//Kha/make', 'android-hl', '-g', 'opengl', '--shaderversion', '300', '--parallelAssetConversion', '4', '--to', 'build_FPS']
Using project from C:\Users\SK\Desktop\Armory\blends\FPS
Info: Publishing project, check console for details.

Using Kha (6e3c4f0a) from C:\Users\SK\Desktop\Armory\Armory\armsdk\Kha
Creating Kha project.
SyntaxError: Unexpected identifier
    at new AsyncFunction (<anonymous>)
    at fs.readFile (C:\Users\SK\Desktop\Armory\Armory\armsdk\Kha\Tools\khamake\out\ProjectFile.js:52:17)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Error: khafile.js did not call resolve, no project created.
Finished in 2.2711904048919678
Build failed, check console
[FPS.zip](https://github.com/armory3d/armory/files/4227508/FPS.zip)
[FPStest.zip](https://github.com/armory3d/armory/files/4227512/FPStest.zip)


```
Khafile used: `project.addLibrary("colyseus-hx")`
When not specifying that this library is used the project funnily builds fine for Browser, but another error shows up again when publishing for Android:
```
Compiling shader 8 of 8 (painter-text.frag.glsl).
File "_build/src/generators/hl2c.ml", line 549, characters 31-37: Assertion failed

Haxe compiler error.
Finished in 9.77964472770691
Build failed, check console
```

**System**
Blender: 2.81
Armory: v2020.2 ($Id: 29eed7c87a5edde6fb0a5ff1814d57116f09cb46 $)
OS: Win 10
Graphics card: GTX 1060

[FPStest.zip](https://github.com/armory3d/armory/files/4227514/FPStest.zip)

**Comment by Simonrazer** [comment]
When trying to publish to Windows(C) the second error shows up regardless of if the Khafile was specified (same test file works).

**Comment by sh-dave** [comment]
> File "_build/src/generators/hl2c.ml", line 549, characters 31-37: Assertion failed

Looks like a HL compiler error, maybe open an issue in the haxe repo?

**Comment by Simonrazer** [comment]
@sh-dave  Did that https://github.com/HaxeFoundation/haxe/issues/9211
