### ISSUE TITLE
Missing forward rendering path in latest build

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#160]
I tried forward rendering after we had the chat on tweeter. `armory/blender/data/data.blend` is missing `forward_path` node tree (I checked it) so when I'm trying to build with `Forward` renderer I get this:

```py
Traceback (most recent call last):
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/arm/props_ui.py", line 524, in execute
    make_renderer.check_default()
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/arm/make_renderer.py", line 170, in check_default
    make_renderer(bpy.data.cameras[0])
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/arm/make_renderer.py", line 15, in make_renderer
    load_library('forward_path', 'armory_default')
  File "/home/razvan/Itch/Armory3D/Armory/armsdk//armory/blender/arm/make_renderer.py", line 196, in load_library
    ref.use_fake_user = True
AttributeError: 'NoneType' object has no attribute 'use_fake_user'
```

**Comment by luboslenco** [comment]
Build 9 should be fine I think, but I screwed up latest git version - forward path now [restored](https://github.com/armory3d/armory/commit/41d84927d5e4fafd4f45b3540ad84cf615df63c3). :)

**Comment by razvanc-r** [comment]
Yes, they have been restored... but now I'm getting a different error :D. Yeah, so I'm using github master (both armory & iron):

```haxe
Trace: TypeError: Cannot read property 'data' of null
    at $hxClasses.iron.data.RenderPath.setTarget (krom.js:8324:98)
    at f (krom.js:29600:242)
    at $hxClasses.iron.data.RenderPath.callCurrentStages (krom.js:8297:4)
    at $hxClasses.iron.data.RenderPath.renderFrame (krom.js:8290:8)
    at $hxClasses.iron.object.CameraObject.renderFrame (krom.js:10789:19)
    at $hxClasses.iron.Scene.renderFrame (krom.js:3275:15)
    at iron_App.render (krom.js:1984:21)
    at Function.kha_System.render (krom.js:14929:3)
    at kha_SystemImpl.renderCallback (krom.js:15020:13)
```

**Comment by luboslenco** [comment]
Ahah, pushed a fix to https://github.com/armory3d/iron/commit/365fb3d8325fa31b38d6311ef94ba71670e8419f which makes *forward_low* path work for me again.

For which preset are you getting this error? Can you try to `git pull` iron repo and do *Clean - Clean Project* in case something got 'stuck' there?

'Forward Low' renders directly to framebuffer so that is the one meant for mobile browsers and similar, but there is no post processing as a result so it looks worse. 'Forward' and 'Forward High' presets do have post-processing just like deferred paths. (SSAO and SSR needs to be 're-added' though, will fix soon).

**Comment by razvanc-r** [comment]
Well, I pulled the latest `iron` but I get the same error, even after `Clean - Clean Project`. Tried both `Forward` & `Forward Low`, same result...

**Comment by luboslenco** [comment]
Tested 'Forward' using Build 9 on Windows and it also works for me (the low preset is broken there). I am currently doing some work there so it's tough to pinpoint these on the fly when using git versions. Will retest on all OSs once new builds get finished.

![capture](https://cloud.githubusercontent.com/assets/3685704/24330412/a2a2e4cc-121d-11e7-8cff-e9ad3d603b80.PNG)

**Comment by razvanc-r** [comment]
If you have any idea how I would be able to help debugging at my end I'm open to suggestions :)

**Comment by luboslenco** [comment]
I will merge the stuff I have been working on and will be happy to retest again then, will ping you - thanks! :)

**Comment by luboslenco** [comment]
Oh, this should be back to normal in Build 10.
