### ISSUE TITLE
Unable to run using a Viewport Camera under Linux in build 10

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#163]
Play in viewport or play fails with the following traceback:

<pre>
Traceback (most recent call last):
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/props_ui.py", line 540, in execute
    make.play_project(True)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/make.py", line 341, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/make.py", line 259, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/make.py", line 91, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/exporter.py", line 2451, in execute
    self.export_object(bo, self.scene)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/exporter.py", line 1407, in export_object
    self.post_export_object(bobject, o, type)
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/exporter.py", line 2894, in post_export_object
    navigation_trait['parameters'] = [arm.utils.get_ease_viewport_camera()]
  File "/home/artur/Applications/Armory3d/armsdk//armory/blender/arm/utils.py", line 82, in get_ease_viewport_camera
    return addon_prefs.ease_viewport_camera
AttributeError: 'ArmoryAddonPreferences' object has no attribute 'ease_viewport_camera'

</pre>

If I uncheck the "Viewport Camera" in the Armory player options, the project plays normaly.

Edited: forgot to mention that this happens on every project that enables Viewport Camera: scene4.blend for example.

I also tested this under macOS and is working ok.

System: Solus 2017.04.18.0 64-bit
GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by luboslenco** [comment]
Is this when using Armory in standard Blender installation? If so - try to install the latest armory.py from Blender add-on preferences (basically doing the [setup](http://armory3d.org/manual/getting_started/setupaddon.html) again). Should prevent this in the future by at least printing a warning into the console..

**Comment by arturjpv** [comment]
Ok, :-)

It was using Armory Blender executed from Itch.io. But I've been playing these days with a custom Blender build and Armory regular addon installation. When accessing the addons preferences I was getting a warning of multiple addons with the same name, so I guess it was mixing my addon stored in .config/blender/2.78/scripts/addons and the included in Armory bundled Blender.

After removing the one from .config/blender/2.78/scripts/addons everything is working.

**Comment by arturjpv** [comment]
Closing the issue!
