### ISSUE TITLE
Modifying node connections while playing in viewport causes errors

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory#165]
**Issue:** Modifying node connections while playing in viewport causes subsequent builds played in viewport to spew errors in the terminal log and not run correctly. A white border appears around the viewport but the game doesn't actually appear to be running.

![viewporterror](https://cloud.githubusercontent.com/assets/1477787/25708982/027388f0-30b6-11e7-87df-1ecfd0a4480b.png)

From the terminal log:
```
... snip ...
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Trace: TypeError: Cannot read property 'bytes' of undefined
    at $hxClasses.kha.graphics4.FragmentShader [as __class__] (krom.js:28630:53)
    at Function.kha_Shaders.init (krom.js:16897:37)
    at Function.kha_SystemImpl.init (krom.js:17244:14)
    at Function.kha_System.init (krom.js:17024:17)
    at Function.Main.start (krom.js:181:13)
    at Function.Main.main (krom.js:174:7)
    at krom.js:31946:6
```

When mouse is moved the following message appears:
```
Trace: TypeError: Cannot read property 'sendMoveEvent' of undefined
    at kha_SystemImpl.mouseMoveCallback (krom.js:17208:22)
```

When a key is pressed the following message appears:
```
Trace: TypeError: Cannot read property 'sendDownEvent' of undefined
    at kha_SystemImpl.keyboardDownCallback (krom.js:17188:26)
```

**Work around:** Do a "Clean" > "Clean Project" from the Render Properties' Armory Player section, then run in viewport again

**Comment by luboslenco** [comment]
Modifying material nodes at runtime should now work as expected. Modifying logic nodes still needs work - will fix at https://github.com/armory3d/armory/issues/102.
