### ISSUE TITLE
Error on build, array iterator out of range for export_mesh_fast in exporter.py

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#167]
`Array iterator out of range: (index 1)
Traceback (most recent call last):
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\props_ui.py", line 543, in execute
    make.play_project(True)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 340, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 258, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 91, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 2502, in execute
    self.export_objects(self.scene)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 2368, in export_objects
    self.do_export_mesh(objectRef, scene)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 1832, in do_export_mesh
    vert_list = self.export_mesh_fast(exportMesh, bobject, fp, o, om)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 1695, in export_mesh_fast
    mat = exportMesh.materials[poly.material_index]
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

location: <unknown location>:-1

location: <unknown location>:-1`

Appears your loop may be one off?

**Comment by luboslenco** [comment]
Can you send me the blend file (just the mesh causing this would be enough)?

Seems to be querying more materials than the mesh has assigned. Is there a multi-material mesh? Or maybe some left overs from removed material, no idea, would need to take a look. :)

**Comment by fractalfederation** [comment]
Blend file in zip.
[bottle.zip](https://github.com/armory3d/armory/files/997943/bottle.zip)

**Comment by luboslenco** [comment]
The error should be gone using this patch, thanks for report!
https://github.com/armory3d/armory/commit/78b9bd0092e749cc28e66889f60527135e68bd86

The trouble was that Blender assigned only a subset of faces to the material, and pointed remaining faces to next material slot, which does not exist. Armory will now handle this and revert to the existing slot when this happens.
![blmat](https://cloud.githubusercontent.com/assets/3685704/26017658/08e54456-376b-11e7-995f-6cf45a2f7863.jpg)

**Comment by fractalfederation** [comment]
Thanks! That worked perfectly.

**Comment by luboslenco** [comment]
Sounds good!
