### ISSUE TITLE
Running blender in background mode fails

### ISSUE THREAD

**Issue by tong** [armory3d/armory#1710]
**Description**
Running blender in background mode fails with armory addon.

**To Reproduce**
Start blender in background mode:
`blender -b test.blend`

```sh
Blender 2.82 (sub 7) (hash 375c7dc4caf4 built 2020-05-13 23:06:57)
Read prefs: /home/tong/.config/blender/2.82/config/userpref.blend
psutil available
Exception in module register(): /usr/share/blender/2.82/scripts/addons/object_collection_manager/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/usr/share/blender/2.82/scripts/addons/object_collection_manager/__init__.py", line 98, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Object Mode')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 34, in register
    arm.keymap.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/keymap.py", line 9, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Window', space_type='EMPTY', region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 34, in register
    arm.keymap.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/keymap.py", line 9, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Window', space_type='EMPTY', region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 34, in register
    arm.keymap.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/keymap.py", line 9, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Window', space_type='EMPTY', region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 380, in on_load_post
    bpy.ops.arm_addon.start()
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 34, in register
    arm.keymap.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/keymap.py", line 9, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Window', space_type='EMPTY', region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201


Read blend: /home/tong/dev/game/gamma/test.blend
Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 23, in register
    arm.props_traits_props.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/props_traits_props.py", line 149, in register
    bpy.utils.register_class(ArmTraitPropWarning)
ValueError: register_class(...): already registered as a subclass 'ArmTraitPropWarning'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 23, in register
    arm.props_traits_props.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/props_traits_props.py", line 149, in register
    bpy.utils.register_class(ArmTraitPropWarning)
ValueError: register_class(...): already registered as a subclass 'ArmTraitPropWarning'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201
Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 23, in register
    arm.props_traits_props.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/props_traits_props.py", line 149, in register
    bpy.utils.register_class(ArmTraitPropWarning)
ValueError: register_class(...): already registered as a subclass 'ArmTraitPropWarning'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201

Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 380, in on_load_post
    bpy.ops.arm_addon.start()
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.82/scripts/addons/armory.py", line 260, in execute
    start.register(local_sdk=local_sdk)
  File "/home/tong/sdk/ArmorySDK//armory/blender/start.py", line 23, in register
    arm.props_traits_props.register()
  File "/home/tong/sdk/ArmorySDK//armory/blender/arm/props_traits_props.py", line 149, in register
    bpy.utils.register_class(ArmTraitPropWarning)
ValueError: register_class(...): already registered as a subclass 'ArmTraitPropWarning'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201



Blender quit
```

**System**
Blender: Blender 2.82 (sub 7) (hash 375c7dc4caf4 built 2020-05-13 23:06:57)
Armory: 130434a541f2a9fa6c49f96d9ddd70c619bb7481
OS: Arch Linux x86_64 5.6.13-arch1-1
Graphics card: NVIDIA GM206 [GeForce GTX 960]

**Comment by MoritzBrueckner** [comment]
Thanks for reporting! Will be fixed in https://github.com/armory3d/armory/pull/1711
