### ISSUE TITLE
Build error, rename file failed, busy or locked

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#173]
`Exporting asset 1 of 1 (smaa_area.png).
Reexporting smaa_area
fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EBUSY: resource busy or locked, rename 'C:\Users\blake\Documents\blender\build\window\krom\smaa_area.png.temp' -> 'C:\Users\blake\Documents\blender\build\window\krom\smaa_area.png'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at ChildProcess.process.on (C:\Users\blake\Downloads\Armory3D\Armory_p10a\armsdk\win32\Kha\Tools\khamake\out\ImageTool.js:63:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 Build failed, check console
`
[beer.zip](https://github.com/armory3d/armory/files/998543/beer.zip)

**Comment by fractalfederation** [comment]
If you delete the UV Map from the * tab, it will work, assuming you are not using a Texture Coordinates node, with the UV option connected to a shader node using a noodle. If there is no Texture Coordinate node but the mesh has a UV Map, it defaults to the UV Map. If there is no UV Map, it defaults to something else. If the material has the Texture Coordinate node set to UV, it does not default to something else, even though the UV Map has been deleted.

Hope this helps!

**Comment by fractalfederation** [comment]
This issue may be related, when I removed the meshes using UV Maps, this error #172 did not happen during build.

**Comment by fractalfederation** [comment]
This was happening on the 10a build. Once I updated to latest armory and kha+submodules, issue does not occur.

**Comment by fractalfederation** [comment]
I just did git pull origin master for armory and tried to render my scene (nothing has changed) and I am getting this error again.


`Compiling shader 1 of 1 (ChairFabric_shadowmap.frag.glsl).
Compiling shader 1 of 1 (ChairFabric_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Coffee_mesh.frag.glsl).
Recompiling Coffee_mesh.frag
Compiling shader 1 of 1 (Coffee_mesh.vert.glsl).
fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'C:\Users\blake\Documents\blender\build\html5-resources\Coffee_mesh.frag.essl.temp' -> 'C:\Users\blake\Documents\blender\build\html5-resources\Coffee_mesh.frag.essl'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at ChildProcess.child.on (C:\Users\blake\Downloads\Armory3D\Armory\armsdk\win32\Kha\Tools\khamake\out\ShaderCompiler.js:356:44)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 Build failed, check console`

**Comment by luboslenco** [comment]
Did you do anything in the Blender while the build was in progress? Does it happen each time or randomly? Any change after project clean?

**Comment by fractalfederation** [comment]
I couldn't figure out how to reopen this issue and also realized it wasn't the exact same error, so I just made a new issue. I will clean project and cache and try again.
