### ISSUE TITLE
Build error when Use Nodes not enabled for Compositing

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#177]
```
Armory v17.05
OS: win, Target: krom, GAPI: direct3d11
Traceback (most recent call last):
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\props_ui.py", line 507, in execute
    make.play_project(False)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make.py", line 342, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make.py", line 260, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make.py", line 77, in export_data
    make_renderpath.build_node_trees(assets_path)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 37, in build_node_trees
    build_node_tree(cam, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 62, in build_node_tree
    buildNode(dat['stages'], rn, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 713, in buildNode
    buildNode(stages, stageNode, node_group)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 590, in buildNode
    make_draw_compositor(stage, node_group, node, with_fxaa=with_fxaa)
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 239, in make_draw_compositor
    compositor_defs = make_compositor.parse_defs(bpy.data.scenes[0].node_tree) # Thrown in scene 0 for now
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make_compositor.py", line 7, in parse_defs
    rn = nodes.get_node_by_type(node_group, 'COMPOSITE')
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\nodes.py", line 20, in get_node_by_type
    for node in node_group.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'

location: <unknown location>:-1

location: <unknown location>:-1

```

If you want me to wait awhile before reporting something, I will. Not sure if this is helpful or just annoying lol

**Comment by luboslenco** [comment]
No, not annoying at all. Having all of it reported here is super handy when fixing stuff. Might take some time to sort it all but will get there. Sorry for your trouble though, tons more work to do. :)

**Comment by luboslenco** [comment]
Should be good now.
