### ISSUE TITLE
Clean Project fails on files copied with read-only

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#179]
```
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Traceback (most recent call last):
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\props_ui.py", line 705, in execute
    make.clean_project()
  File "C:/Users/blake/Downloads/Armory3D/Armory/armsdk//armory/blender\arm\make.py", line 481, in clean_project
    shutil.rmtree('build')
  File "C:\Users\blake\Downloads\Armory3D\Armory\2.78\python\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\blake\Downloads\Armory3D\Armory\2.78\python\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\blake\Downloads\Armory3D\Armory\2.78\python\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\blake\Downloads\Armory3D\Armory\2.78\python\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\blake\Downloads\Armory3D\Armory\2.78\python\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'build\\window\\krom\\jgrm_D.jpg'

location: <unknown location>:-1

location: <unknown location>:-1
```

The file was set to read-only before Armory copied it to the build/window/krom/ directory. I guess you need to check before copy and disable read-only on the copy if it's enabled.

**Comment by luboslenco** [comment]
Patched in https://github.com/armory3d/armory/commit/862fea67251d31d8b1a19bcb2a1004028751fc47.
