### ISSUE TITLE
Spawn Object node returns error; Does not compile

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1870]
Thank you for contributing to Armory!

**Description**
When Spawn Object node is used, The following error appears:
```
Error: Traceback (most recent call last):
  File "D:\Armory\ArmorySDK//armory/blender\arm\props_ui.py", line 543, in execute
    make.play()
  File "D:\Armory\ArmorySDK//armory/blender\arm\make.py", line 482, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\Armory\ArmorySDK//armory/blender\arm\make.py", line 370, in build
    export_data(fp, sdk_path)
  File "D:\Armory\ArmorySDK//armory/blender\arm\make.py", line 94, in export_data
    make_logic.build()
  File "D:\Armory\ArmorySDK//armory/blender\arm\make_logic.py", line 32, in build
    build_node_tree(tree)
  File "D:\Armory\ArmorySDK//armory/blender\arm\make_logic.py", line 80, in build_node_tree
    build_node(node, f)
  File "D:\Armory\ArmorySDK//armory/blender\arm\make_logic.py", line 184, in build_node
    inp_name = build_default_node(inp)
  File "D:\Armory\ArmorySDK//armory/blender\arm\make_logic.py", line 259, in build_default_node
    default_value = inp.default_value
AttributeError: 'NodeSocketShader' object has no attribute 'default_value'
```

**System**
Blender: 2.83
Armory:  v2020.9 ($Id: c1f8fc52f6f5ba3036b777670bbdd973e9123306 $)
OS: Windows

**Test File**
[SpawnObjTest.zip](https://github.com/armory3d/armory/files/5228947/SpawnObjTest.zip)

**Comment by knowledgenude** [comment]
It is not compiling without an input connected to it and it is not happening only to this node, but to all nodes that have a `SocketShader` input.

**Comment by MoritzBrueckner** [comment]
It isn't related to that commit, but it's fixed now: https://github.com/armory3d/armory/pull/1871. Thanks for reporting!
