### ISSUE TITLE
AttributeError: 'ArmoryAddonPreferences' object has no attribute 'ease_viewport_camera'

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#195]
Hi Lubos,

Getting this error on many of the example projects when trying with 11a build on Linux. Occurs when trying to play.

Traceback (most recent call last):
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/props_ui.py", line 551, in execute
    make.play_project(True)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/make.py", line 362, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/make.py", line 273, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/make.py", line 92, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/exporter.py", line 2476, in execute
    self.export_object(bo, self.scene)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/exporter.py", line 1431, in export_object
    self.post_export_object(bobject, o, type)
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/exporter.py", line 2888, in post_export_object
    navigation_trait['parameters'] = [str(arm.utils.get_ease_viewport_camera()).lower()]
  File "/home/guzzard/bin/Armory//armsdk//armory/blender/arm/utils.py", line 94, in get_ease_viewport_camera
    return addon_prefs.ease_viewport_camera
AttributeError: 'ArmoryAddonPreferences' object has no attribute 'ease_viewport_camera'

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Hello!

Can you try to (re)install the latest `armory.py` script from armsdk folder? Or check if there is a conflict/multiple armory add-ons running in *Blender User Preferences - Add-ons tab*?

`armory.py` script changed a little and it looks like there is an older version stuck somewhere.

**Comment by guzzard** [comment]
@luboslenco yes, multiple addons was the problem.

I had installed the armory addon in the "normal" blender installed on my system, and this was loaded by the armory build of blender as well, which resulted in a conflict i guess. Removed it, now the armory build works as expected, thanks!
