### ISSUE TITLE
Houston we have a Problem, a "too many uniforms" problem - html5 - webGL2.0

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2020]
Does anyone came across to this error with armory and know what is actually causing this issue?

I suspect my 3d model is too complex and I am searching after some directions in order to run it correctly in Armory and making it more simple.

What is a "uniform" and how does it translate in Blender?

Any input will be much appreciated.
Thanks

**Comment by MoritzBrueckner** [comment]
A [uniform](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)) is like a shader variable that's uniform to all "executions" of that shader in a particular draw call (draw call = tell the GPU it should draw something). It is a bit like a global variable that can be used to pass parameters to a shader.

So it is probably caused by a too complex material or world shader. Maybe the only way to find the exact cause is to check all generated .glsl files in `build/compiled/Shaders/` and search for a file with many uniforms at the top (they use the keyword `uniform` so they're easy to find). But (if I'm not mistaken) the amount of variables is not the crucial factor, it's their size. A vec4 will take 4 times the space a float takes, an array or a sampler (texture) may take even more space.

To verify your findings you can hide all meshes with that particular material.

**Comment by onelsonic** [comment]
thanks @MoritzBrueckner so I removed one by one any complex elements, materials, etc, from my 3D model and looked at all the GLSL materials and else and texted every time and it turns out it to be the following : 

An Armory3D project will just stop with a "too many uniforms" error only in specific cases:
It occurs ONLY with Adreno GPUs which all have a pretty low Vertex Uniform and Fragment Uniform counts in their hardware: 256 vs usually 1024 for Mali GPUs while being much faster in 3D than Mali GPUs. 

When you export a 3D model with a complex Armature and lot of Bones it will simply crash with this error on Adreno GPUs but it will work on an old and 70 times slower Mali GPU.

I checked other engines, Unreal, Unity and they do have 3D models with complex Armature animation running correctly on Adreno GPU. (Ex: Genshin Impact which is running using Unity).

This seems to be a problem with Armory and Adreno GPU while handling Armatures and Bones.
The way Armatures and bones are processed using and here I guess "Uniforms" is causing the issue.

For now the best workaround I found is using over simplified Armatures will low bones counts. (so no moving hairs or cloths, etc...)

**Comment by QuantumCoderQC** [comment]
Hi @onelsonic, Thanks for the info.

Would you be able to the following checks and see if there are any differences please:

1. Remove ALL textures from the model and use only a simple diffuse shader. Keep the high number of bones and the complex armature.

2. There is an option in the Object settings panel of Armory that says "Skinned object" or similar. Try it with your character and check again.

Also, does your "Character" object have more than one sub-meshes ?

Best Regards,
QC

**Comment by onelsonic** [comment]
1. is not working: crashing with "too many uniforms" on Adreno and running smooth even on old Mali GPU.

2. There is a "dynamic usage" settings for the object, I activated it, but same as above.

Then this 2013/2014 thread seems similar to what I am experiencing with modern high end Adreno GPU:
[https://developer.qualcomm.com/comment/6972](https://developer.qualcomm.com/comment/6972)

Issue probably come from this :
The GLES shading language spec:
http://www.khronos.org/files/opengles_shading_language.pdf
Chapter 12, Appendix A, section 5 "Limitations for ES 2.0"
_Uniforms (excluding samplers):
In the vertex shader, support for all forms of array indexing is mandated. In the fragment shader, support 
for indexing is only mandated for constant integral expressions._

**Comment by onelsonic** [comment]
Hi there, after further investigation and test.

**Comment by N8n5h** [comment]
Haven't delved too deep into armory's bone animations, but from what I could gather:
https://github.com/armory3d/iron/blob/master/Sources/iron/object/BoneAnimation.hx 
The `skinBuffer` float array from the `BoneAnimation` class is passed under the link `_skinBones` here https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/Uniforms.hx#L989
which is used by this shader https://github.com/armory3d/armory/blob/master/Shaders/std/skinning.glsl
and how it's used when writing vertex shaders https://github.com/armory3d/armory/blob/master/blender/arm/material/make_skin.py

If too many uniforms may be tripped probably is because of that uniform.

**Comment by onelsonic** [comment]
thanks @N8n5h, I checked all codes you mentioned and run a few tests and succeed to localise the issue.
It comes from this line here :
https://github.com/armory3d/armory/blob/48952e04a8f29379e55e1a368dc86101cf918eed/Shaders/std/skinning.glsl#L3

On Adreno GPUs (skinMaxBones * 2) is too high for the hardware. (Or badly supported, not sure...)

Hard coding the 'skinMaxBones * 2' value to 245 partially fix the problem as we just limit it to how many uniforms Adreno GPU are supporting.
`uniform vec4 skinBones[245];`

not sure why 245 works, when I think it should technically be 256.

Also changing this line here has no effect whatsoever on the GLSL shader:
	`public static var skinMaxBones = 128;`
https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/BoneAnimation.hx#L17

Looking at how Adreno's work :
- max vertex uniform vectors : 256 (> 1024 on Mali)
- max vertex uniform components : 1024 (> 4096 on Mali)
![adreno-5xx](https://user-images.githubusercontent.com/53947594/99987799-29e0ed00-2db1-11eb-917b-eac8874002fb.png)

I read that Adreno GPU's OpenGL was bogus somehow and not sure if it is still the case now...
Also Adreno GPU's are the currently the fastest on android and the Google Pixel's phones all have it.
Reported bogus drivers here:
[https://github.com/godotengine/godot/issues/12816#issuecomment-355991771](https://github.com/godotengine/godot/issues/12816#issuecomment-355991771)
[https://developer.qualcomm.com/comment/6972](https://developer.qualcomm.com/comment/6972)

some proposals for fix this for Adreno: 
1: should bones skinning use texture data instead of uniforms? Will it be as fast?
2 : is there a way to force the use of OpenGL ES2 instead of ES3 for android or webGL2.0 to test it? It might fix this issue.
3: then not sure if it is related but when I try to set the Max bones parameters manually, here : the export crashes with the below:
<img width="214" alt="2020-11-23 16_22_44-Blender  C__Users_devWin10_Desktop_seed2_seed_bfirst1 blend" src="https://user-images.githubusercontent.com/53947594/99980138-30b73200-2da8-11eb-9e48-107bd39f9cde.png">
to 
<img width="177" alt="2020-11-23 17_34_39-Blender  C__Users_devWin10_Desktop_seed2_seed_bfirst1 blend" src="https://user-images.githubusercontent.com/53947594/99988817-3f0a4b80-2db2-11eb-9630-015df1ecfa27.png">

_compilation crash logs:_
```
Exporting Scene
Traceback (most recent call last):
  File "C:\armory/blender\arm\props_ui.py", line 870, in execute
    make.build(item.arm_project_target, is_publish=True, is_export=True)
  File "C:\armory/blender\arm\make.py", line 383, in build
    export_data(fp, sdk_path)
  File "C:\armory/blender\arm\make.py", line 125, in export_data
    ArmoryExporter.export_scene(bpy.context, asset_path, scene=scene, depsgraph=depsgraph)
  File "C:\armory/blender\arm\exporter.py", line 154, in export_scene
    cls(context, filepath, scene, depsgraph).execute()
  File "C:\armory/blender\arm\exporter.py", line 2139, in execute
    self.export_objects(self.scene)
  File "C:\armory/blender\arm\exporter.py", line 2001, in export_objects
    self.export_mesh(mesh_ref)
  File "C:\armory/blender\arm\exporter.py", line 1436, in export_mesh
    exporter_opt.export_skin(self, bobject, armature, vert_list, out_mesh)
  File "C:\armory/blender\arm\exporter_opt.py", line 301, in export_skin
    log.warn(bobject.name + ' - ' + str(bone_count) + ' bones found, exceeds maximum of ' + str(max_bones) + ' bones defined - raise the value in Camera Data - Armory Render Props - Max Bones')
NameError: name 'log' is not defined

```

**Comment by MoritzBrueckner** [comment]
> not sure why 245 works, when I think it should technically be 256.

Not sure, but I guess it's because there are still other uniforms somewhere that add to this count.

> then not sure if it is related but when I try to set the Max bones parameters manually, here : the export crashes with the below:

Added a fix, this was not related to your changes: https://github.com/armory3d/armory/pull/2021

**Comment by onelsonic** [comment]
Digging into this problem,
another possible solution will be to rewrite the GPU skinning shader to use "Uniform Buffer Object" instead of "Vertex Uniform".
https://github.com/armory3d/armory/blob/master/Shaders/std/skinning.glsl

**Comment by onelsonic** [comment]
Digging into this problem,
another possible solution will be to rewrite the GPU skinning shader to use "Uniform Buffer Object" instead of "Vertex Uniform".
https://github.com/armory3d/armory/blob/master/Shaders/std/skinning.glsl

**Comment by N8n5h** [comment]
The size of `skinBuffer`  from `BoneAnimation` is computed here https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/BoneAnimation.hx#L73, 
```Haxe
this.skinBuffer = new Float32Array(skinMaxBones * boneSize);
```
so it's weird that reducing the value of `skinMaxBones` doesn't change anything. Have you tried drastically reducing the value to see if it has the same effect still?
Also be sure to check to what value armory writes the `const int skinMaxBones` in compiled/Shaders/compiled.inc.

**Comment by onelsonic** [comment]
setting skinMaxBones to 1 or 122 in BoneAnimation.hx has no effect, the animation will play correctly on Mali GPU but crash on Adreno. Yes strange, there is probably something overwriting its value when running. 
https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/BoneAnimation.hx#L17

I will provide a file so it can illustrate this issue :
Blend File: 
https://github.com/onelsonic/armory_tests/blob/master/animation-android-adreno-bug/link.blend

You can test the animation and run it with Google Chrome on Android (Adreno and Mali GPU)
https://onelsonic.github.io/animation-android-adreno-bug/index.html
This issue comes from how OpenGL GPU skinning is rendered on Android with Adreno GPU, so the same issue will occur natively on Android as well.

Solution: 
Rewriting the "uniform vec4 skinBone" here :
https://github.com/armory3d/armory/blob/48952e04a8f29379e55e1a368dc86101cf918eed/Shaders/std/skinning.glsl#L3
using either **texture data** or **Uniform Buffer** not sure which one is bigger on Adreno.

[full adreno OpenGL specs link]
(https://user-images.githubusercontent.com/53947594/100106245-9bc83d80-2e68-11eb-8981-2720a47f915e.png)

**Comment by onelsonic** [comment]
<img width="171" alt="2020-11-24 21_05_08-Blender  C__Users_devWin10_Desktop_seed2_seed_bfirst1 blend" src="https://user-images.githubusercontent.com/53947594/100145623-e19cfa00-2e98-11eb-9d45-94a9e2bcf76f.png">
This is what is overwriting the skinMaxBones value.
If set manually to 122 (thanks to fix @MoritzBrueckner) --> 122*2 = 244 we get the same as hard coding the value to 244.
Stripping the extra bones. It set to Auto it will default to an automatic calculated value.

I think **Texture buffer objects** might be the way to fix this.

(below is what we should be aware of using if using **Texture buffer objects**)
https://gamedev.stackexchange.com/questions/174019/instancing-and-gpu-skinning

Anyone succeed to replicate this issue on Adreno?

**Comment by onelsonic** [comment]
my blender file got corrupted when posting on github, I re-uploaded it here :
[link.7z](https://github.com/onelsonic/armory_tests/raw/master/animation-android-adreno-bug/link.7z)

**Comment by QuantumCoderQC** [comment]
@onelsonic Thanks for the insights. I am currently working on improving the animation system for Armory3D. Would it help fix this issue if we use `uniform Mat4 skinBones[maxBones]` instead of `uniform Vec4 skinBones[maxBones * 3]`. (its maxBones * 3 now because I will be including the scale of the bones too. So, 2 for dual quat and 1 for scale.)

So, will going from Vec4 to Mat4 reduce the number of uniforms and maybe fix this issue?

**Comment by MoritzBrueckner** [comment]
According to [this](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)#Implementation_limits), the allowed number of uniforms does depend on the size of the used uniforms in OpenGL. So if I understand it correctly, using a 4x4 matrix would take away 4 "components" more than 3 vec4s, but I might be mistaken here and it actually might vary between different platforms and GPUs. The linked page states for example that on some (especially older) GPUs vectors always take 4 components independent of their size. Maybe try to set `maxBones` to a value close to the allowed treshold on your system and then check whether it gets worse or better when using matrices.

I think the same holds true for DirectX/HLSL, at least I had some [issue with that in the past](https://github.com/Kode/krafix/issues/74) where data was always aligned in blocks of 4 components which Kha couldn't handle very well.

**Comment by onelsonic** [comment]
What @MoritzBrueckner says

then the above issue is Hardware specific on Adreno/qualcomm GPU but also tight to the way bones animations are handle in Armory which uses a too restrictive format : "vertex uniform" not really fit for the Adreno platform.

I found this issue occuring on Adreno 200/300/400 and 500 series so far and I have not tested the 600 series yet...
Someone with a Android Adreno GPU with the 600 series can test it here :

- Can you see the animation ? Yes/No
https://onelsonic.github.io/animation-android-adreno-bug/
(should be live in 1h, Github CDN)

- If not please report the following : 
what is your OpenGL specs?
(you can use this) https://play.google.com/store/apps/details?id=com.realtechvr.glview
or this : webGL2 specs
https://webglreport.com/?v=2

and report on these values:
- max vertex uniform vectors : ???
- max vertex uniform components : ????


To overcome this a solution is to step away from "uniform" all together as being too restrictive on Adreno.

Not 100% sure but it seems like Unity has the same issue and fixed it in 2018 :
https://issuetracker.unity3d.com/issues/materialpropertyblock-adreno-devices-returning-wrong-result-from-materialpropertyblock

**_Most reliable workaround is to use unsigned integer variables for array indexing_** for the bones animations.

Also there is another issue which is maybe this will fix it,
if you have a long animation let's say 100/150 frames / Armory will just take an eternity to process it (45min to 1h).

**Comment by MoritzBrueckner** [comment]
It's indeed fine on a Mali GPU and Android 10, I can see the animation of a waving Link on a Mali-G72.

| GL Version | Max. Vertex Uniform Vectors | Max. Vertex Uniform Components |
| --- | --- | --- |
| OpenGL ES 3.2 | 1024 | 4096 |


I also tested it on a cheap crappy tablet with Android 9 and a PowerVR Rogue GE8100 GPU from Imagination Technologies (never heard of it), and the animation also plays but the arms are very buggy and twisted. Specs:


| GL Version | Max. Vertex Uniform Vectors | Max. Vertex Uniform Components |
| --- | --- | --- |
| OpenGL ES 3.2 | 512 | 2048 |

**Comment by QuantumCoderQC** [comment]
> Not 100% sure but it seems like Unity has the same issue and fixed it in 2018 :
https://issuetracker.unity3d.com/issues/materialpropertyblock-adreno-devices-returning-wrong-result-from-materialpropertyblock
Most reliable workaround is to use unsigned integer variables for array indexing for the bones animations.

From what I see this does not address the issue of exceeding the maximum supported uniforms, rather, how to access each uniform properly from an array. 

I also looked up on texture based animations. Although it is faster and might solve the issues with the limited uniforms, it opens up a host of other issues. 
1. Exporting these animations as textures: Note that each animation can have different number of frames, compression of this data and so on. 
2. For a game engine, Blending animations, IK and FK actions, Bone constraints and Bone parenting are all very essential and must all be done in real-time. These cannot be pre-baked into textures as they have to be processed on the CPU when required.

So, if the engine only plays complex animations with many bones and does not require much of real-time modifications to these animations, having a texture based animation makes sense.

**Comment by QuantumCoderQC** [comment]
yes, I think using uniform buffers here might be a better option. Not sure how one should link this though.

The current linking is defined here https://github.com/armory3d/armory/blob/55cfead0844923d419d75bf4bd677ebed714b4b5/blender/arm/material/make_skin.py#L14

Should this remain the same even if we use uniform buffers?

**Comment by onelsonic** [comment]
> 
> 
> yes, I think using uniform buffers here might be a better option. Not sure how one should link this though.
> 
> The current linking is defined here
> 
> https://github.com/armory3d/armory/blob/55cfead0844923d419d75bf4bd677ebed714b4b5/blender/arm/material/make_skin.py#L14
> 
> Should this remain the same even if we use uniform buffers?

this should help : https://www.geeks3d.com/20140704/gpu-buffers-introduction-to-opengl-3-1-uniform-buffers-objects/
