### ISSUE TITLE
Changing engine breaks blend file, not possible to recover

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#204]
Hi @luboslenco,

I changed engine in armory by mistake and it broke the blend file. I quit without saving and when I loaded the blend file engine was still the wrong one, and it was not possible to change it back. I tried changing to armory, save, restart armory, load file. However, engine was set to cycles engine. Not possible to repair it seems.

**To reproduce:**
1. starting armory
2. open file
3. change to blender engine
4. change back to armory
5. hit play in viewport

**Resulting log:**
Color management: using fallback mode for management
Read new prefs: /home/guzzard/.config/blender/2.78/config/userpref.blend
found bundled python: /home/guzzard/bin/Armory/2.78/python
which: no nvcc in (/home/guzzard/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:
/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
read blend: /home/guzzard/Development/Armory3D/scene1/scene1.blend
search for unknown operator 'ARM_OT_play_in_viewport', 'ARM_OT_play_in_viewport'
search for unknown operator 'ARM_OT_play', 'ARM_OT_play'
search for unknown operator 'ARM_OT_play_in_viewport', 'ARM_OT_play_in_viewport'
search for unknown operator 'ARM_OT_play', 'ARM_OT_play'
Traceback (most recent call last):
  File "/home/guzzard/bin/Armory/2.78/scripts/addons/armory.py", line 246, in execute
    start.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/start.py", line 34, in register
    arm.nodes_renderpath.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/nodes_renderpath.py", line 933, in register
    bpy.utils.register_class(SSResolveNode)
ValueError: register_class(...): already registered as a subclass

location: /home/guzzard/bin/Armory/2.78/scripts/modules/bpy/ops.py:187

location: /home/guzzard/bin/Armory/2.78/scripts/modules/bpy/ops.py:187
Error: Traceback (most recent call last):
  File "/home/guzzard/bin/Armory/2.78/scripts/addons/armory.py", line 246, in execute
    start.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/start.py", line 34, in register
    arm.nodes_renderpath.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/nodes_renderpath.py", line 933, in register
    bpy.utils.register_class(SSResolveNode)
ValueError: register_class(...): already registered as a subclass

location: /home/guzzard/bin/Armory/2.78/scripts/modules/bpy/ops.py:187

Traceback (most recent call last):
  File "/home/guzzard/bin/Armory/2.78/scripts/addons/armory.py", line 123, in on_scene_update_post
    bpy.ops.arm_addon.start('EXEC_DEFAULT')
  File "/home/guzzard/bin/Armory/2.78/scripts/modules/bpy/ops.py", line 187, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/guzzard/bin/Armory/2.78/scripts/addons/armory.py", line 246, in execute
    start.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/start.py", line 34, in register
    arm.nodes_renderpath.register()
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/nodes_renderpath.py", line 933, in register
    bpy.utils.register_class(SSResolveNode)
ValueError: register_class(...): already registered as a subclass

location: /home/guzzard/bin/Armory/2.78/scripts/modules/bpy/ops.py:187

Armory v17.05
OS: linux, Target: krom, GAPI: opengl
Traceback (most recent call last):
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/props_ui.py", line 551, in execute
    make.play_project(True)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/make.py", line 362, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/make.py", line 273, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/make.py", line 92, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/exporter.py", line 2476, in execute
    self.export_object(bo, self.scene)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/exporter.py", line 1431, in export_object
    self.post_export_object(bobject, o, type)
  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/exporter.py", line 2726, in post_export_object
    if t.enabled_prop == False:
AttributeError: 'RemoveActiveSceneNode' object has no attribute 'enabled_prop'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by Nopotato** [comment]
I am having this problem as well. But when I load my file, it always starts in another engine (usually cycles?) so all my files break. As seen in my other thread https://github.com/armory3d/armory/issues/211 Other people are able to play my broken files fine.

**Comment by FireSlash** [comment]
I hit this as well.

It's unclear how the setting got changed, and it seems to be tricky to recover from, even creating a new blend file doesn't seem to immediately fix it (likely describing the "viral" behavior @Nopotato mentions.

**Comment by luboslenco** [comment]
This should no longer cause trouble - in build 12 there is no more separate 'Armory' entry in render engines list. This is done to make Armory operable both using Cycles and Eevee engines and to keep away from getting more scenes corrupted.
