### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#218]
I get this error when trying to build. I am using 11b but I've done git pull on armory/iron/kha/kore/etc. I also tried again after deleting build directory. 
---------------------------
Armory v17.07
OS: win, Target: html5, GAPI: opengl
Traceback (most recent call last):
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\props_ui.py", line 617, in execute
    make.build_project(target=state.target)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make.py", line 292, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make.py", line 83, in export_data
    world_outputs = make_world.build_node_trees(active_worlds)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make_world.py", line 25, in build_node_trees
    output = build_node_tree(world)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make_world.py", line 46, in build_node_tree
    parse_world_output(world, output_node, context)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make_world.py", line 155, in parse_world_output
    parse_surface(world, surface_node, context)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make_world.py", line 176, in parse_surface
    parse_color(world, color_node, context, envmap_strength_const)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\make_world.py", line 254, in parse_color
    mip_count = write_probes.write_probes(filepath, disable_hdr, mip_count, generate_radiance=wrd.generate_radiance)
  File "C:/Users/blake/Downloads/Armory3D/Armory_p11b_win64/armsdk//armory/blender\arm\write_probes.py", line 71, in write_probes
    'height=' + str(target_h)])
  File "C:\Users\blake\Downloads\Armory3D\Armory_p11b_win64\2.78\python\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\blake\Downloads\Armory3D\Armory_p11b_win64\2.78\python\lib\subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\blake\Downloads\Armory3D\Armory_p11b_win64\2.78\python\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\blake\Downloads\Armory3D\Armory_p11b_win64\2.78\python\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

location: <unknown location>:-1

---------------------------

**Comment by luboslenco** [comment]
Hello,

Can you paste your world nodes or attach blend file for testing? Or is this happening for all scenes? Did it work before?

**Comment by fractalfederation** [comment]
armsdk\win32\Kha\Kore\Tools -- had kraffiti_bin with files and kraffiti with no files, so deleted empty and renamed _bin without _bin. Same problem with krafix

C:\Users\blake\Downloads\Armory3D\Armory_p11b_win64\armsdk\win32\Kha\Tools - all folders empty, git submodule foreach git pull origin master worked. 

Sorry! I thought I got all the modules that have their own git hub. Should of paid closer attention.
