### ISSUE TITLE
Blender 'Reload Scripts' error

### ISSUE THREAD

**Issue by tong** [armory3d/armory#2261]
I've just figured out that we can reload the addon without restarting blender (F3 → Reload Scripts, or click on splash icon → Reload Scripts), but armory fails to do so:

```
Reloading: <module 'bl_operators' from '/usr/share/blender/2.93/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/usr/share/blender/2.93/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/usr/share/blender/2.93/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/usr/share/blender/2.93/scripts/startup/nodeitems_builtins.py'>
gc.collect() -> 32065
Python: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.93/scripts/addons/armory.py", line 469, in execute
    start.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/start.py", line 45, in unregister
    arm.nodes_material.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 54, in unregister
    unregister_nodes()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 46, in unregister_nodes
    nodeitems_utils.unregister_node_categories('ArmMaterialNodes')
  File "/usr/share/blender/2.93/scripts/modules/nodeitems_utils.py", line 172, in unregister_node_categories
    del _node_categories[identifier]
KeyError: 'ArmMaterialNodes'

location: /usr/share/blender/2.93/scripts/modules/bpy/ops.py:132
Error: Python: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.93/scripts/addons/armory.py", line 469, in execute
    start.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/start.py", line 45, in unregister
    arm.nodes_material.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 54, in unregister
    unregister_nodes()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 46, in unregister_nodes
    nodeitems_utils.unregister_node_categories('ArmMaterialNodes')
  File "/usr/share/blender/2.93/scripts/modules/nodeitems_utils.py", line 172, in unregister_node_categories
    del _node_categories[identifier]
KeyError: 'ArmMaterialNodes'

location: /usr/share/blender/2.93/scripts/modules/bpy/ops.py:132

Exception in module unregister(): '/home/tong/.config/blender/2.93/scripts/addons/armory.py'
Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/home/tong/.config/blender/2.93/scripts/addons/armory.py", line 592, in unregister
    bpy.ops.arm_addon.stop()
  File "/usr/share/blender/2.93/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/tong/.config/blender/2.93/scripts/addons/armory.py", line 469, in execute
    start.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/start.py", line 45, in unregister
    arm.nodes_material.unregister()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 54, in unregister
    unregister_nodes()
  File "/home/tong/dev/ARMORY/armsdk//armory/blender/arm/nodes_material.py", line 46, in unregister_nodes
    nodeitems_utils.unregister_node_categories('ArmMaterialNodes')
  File "/usr/share/blender/2.93/scripts/modules/nodeitems_utils.py", line 172, in unregister_node_categories
    del _node_categories[identifier]
KeyError: 'ArmMaterialNodes'

location: /usr/share/blender/2.93/scripts/modules/bpy/ops.py:132


Reloading: <module 'bl_operators' from '/usr/share/blender/2.93/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/usr/share/blender/2.93/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/usr/share/blender/2.93/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/usr/share/blender/2.93/scripts/startup/nodeitems_builtins.py'>
gc.collect() -> 32999
```

**Comment by MoritzBrueckner** [comment]
_Slightly off-topic: I fear that this error is not the only one that will occur when you try to reload the addon, there are many global variables (that might or might not need to be reset) and if I remember this correctly from my work on other addons a few years ago, you have to be very careful with the order in which modules are imported when reloading an addon. Things tend to be a lot more unstable after reloading. So it's probably a lot of work (still should be done eventually) and working on this could be well combined with improving the structure of the Python sources (the current one is a bit chaotic)._

But let's start with the current error, the whole reloading stuff can probably be seen as a bigger project with lots of small steps. @tong do you get this error message before closing Blender? To me it happens only when closing Blender after reloading (before there is no error but also no Armory UI). It happens because the node category seems to be unregistered twice, once when reloading and once when closing Blender and because of that I suspect that there is another "hidden" error so that somehow the node categories don't re-register after reloading.

**Comment by tong** [comment]
Until now the i've got the error message immediately, but just re-tested and now it behaves the same as you describe (?).

I think it's problematic to have any addon behave like this, as it might have influence on blender in general and make (armory) unrelated things break, something to consider a major issue, imho.
