### ISSUE TITLE
Key Missing

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#23]
I opened up a scene I made under Cycles, and tried playing it in the viewport with Armory.  I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\props_ui.py", line 521, in execute
    make.play_project(self, True)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\make.py", line 306, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\make.py", line 199, in build_project
    wrd = bpy.data.worlds['Arm']
KeyError: 'bpy_prop_collection[key]: key "Arm" not found'

location: <unknown location>:-1
```

**Comment by zauberparacelsus** [comment]
Updating my report: it seems to be doing this now for my prior test scene that I had previously gotten working.

**Comment by luboslenco** [comment]
Yes, the reason is putting Armory as a separate engine entry is a bit hacky, since Armory also needs to act like Cycles. If you switch engines around a few times it may go away(or not), but that is not a solution of course. Will be fixed in next build.

**Comment by zauberparacelsus** [comment]
Okay, apparently part of the problem was that the .blend file was saved on a different partition.  On my computer, I've got three hard drives: one for Linux, one for Windows, and the third is a shared drive that is used by both.

```
Warning: Path 'C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender/data/data.blend' cannot be made
relative
Warning: Total files 1 | Changed 0 | Failed 1
Exporting mesh Cube
Exporting mesh Plane
Scene built in 0.011006355285644531
Traceback (most recent call last):
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\props_ui.py", line 521, in execute
    make.play_project(self, True)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\make.py", line 306, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\make.py", line 252, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\make.py", line 113, in export_data
    write_data.write_khafilejs(is_play, export_physics, dce_full=is_publish)
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\write_data.py", line 28, in write_khafi
lejs
    f.write(add_armory_library(sdk_path, 'armory'))
  File "C:\Users\Robert\Downloads\Armory_p01_win32\Armory\armsdk\/armory/blender\write_data.py", line 7, in add_armory_l
ibrary
    return ('project.addLibrary("../' + bpy.path.relpath(sdk_path + '/' + name)[2:] + '");\n').replace('\\', '/')
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\bpy\path.py", line 113, in relpath
    return "//" + _os.path.relpath(path, start)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\ntpath.py", line 574, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'G:'
```

**Comment by luboslenco** [comment]
'key "Arm" not found' fixed in Build 2.
