### ISSUE TITLE
armory is incompatible with some plugins

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#233]
seems to be incompatible with EasyFX & AnimationNodes. I have a few plugins downloaded form the internet and turning them off one by one seems like Armory doesn't like these two in particular. Here is the error log while opening armory with these plugins on:

```
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
Color management: using fallback mode for management
Read prefs: /home/razvan/.config/blender/2.79/config/userpref.blend
found bundled python: /home/razvan/.config/itch/apps/Armory3D/Armory/2.79/python
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/blender/2.79/scripts/addons/blender-osm/__init__.py", line 58, in <module>
    class BlenderOsmPreferences(bpy.types.AddonPreferences):
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/blender/2.79/scripts/addons/sverchok/__init__.py", line 119, in <module>
    settings = importlib.import_module(".settings", __name__)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/razvan/.config/blender/2.79/scripts/addons/sverchok/settings.py", line 2, in <module>
    from bpy.types import AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/blender/2.79/scripts/addons/kaleidoscope/__init__.py", line 110, in <module>
    class Kaleidoscope(bpy.types.AddonPreferences):
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/armory.py", line 17, in <module>
    from bpy.types import Operator, AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/blender/2.79/scripts/addons/BlenderGIS/__init__.py", line 43, in <module>
    from . import prefs
  File "/home/razvan/.config/blender/2.79/scripts/addons/BlenderGIS/prefs.py", line 5, in <module>
    from bpy.types import Operator, Panel, AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/space_view3d_display_tools/__init__.py", line 61, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/space_view3d_brush_menus/__init__.py", line 57, in <module>
    from bpy.types import AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/btrace/__init__.py", line 40, in <module>
    from bpy.types import AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/archipack/__init__.py", line 90, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/io_online_sketchfab/__init__.py", line 44, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/materials_library_vx/__init__.py", line 43, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/mesh_extra_tools/__init__.py", line 105, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/mesh_snap_utilities_line.py", line 42, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/add_advanced_objects_panels/__init__.py", line 39, in <module>
    from bpy.types import (
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : <class 'bpy_types.AddonPreferences'> ref:108  ptr:0x7f7931174418 type:RNAMeta
pyrna_srna_Subtype: error registering 'AddonPreferences'
pyrna_struct_CreatePyObject: could not make type
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/add_advanced_objects_menu/__init__.py", line 80, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/sequencer_kinoraw_tools/__init__.py", line 56, in <module>
    from bpy.types import (
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Traceback (most recent call last):
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/uv_magic_uv/__init__.py", line 63, in <module>
    from . import muv_preferences
  File "/home/razvan/.config/itch/apps/Armory3D/Armory/2.79/scripts/addons/uv_magic_uv/muv_preferences.py", line 31, in <module>
    from bpy.types import AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
measureit: Imported multifiles
archimesh: Imported multifiles
Hello World
Registered Cutout Animation Tools with 20 modules
cmolcore imported with success! v1.01
Registered Animation Nodes with 497 modules.
archipack: ready
startup coa modal operator
```

**Comment by luboslenco** [comment]
Animation nodes seem to work for me, maybe it's triggered by some specific way?

**Comment by razvanc-r** [comment]
@luboslenco remember this bug? :) there were other people also experiencing it, I saw some other issues. I have no idea how it's triggered exactly but I found that some combination of addons make the bug happen, not one particular addon.

You can try this with 2 addons: if you turn on Animaton Nodes AND THEN turn on Kaleidoscope (https://github.com/blenderskool/kaleidoscope), Kaleidoscope gives the error. If you turn off Animation Nodes after all this, this is the log for some reason:

```
