### ISSUE TITLE
Can not debugging with Kode studio

### ISSUE THREAD

**Issue by SaxonGao-SZ** [armory3d/armory#2333]
ArmorySDK: 202109

1. first step: click "build" button in "Armory Exporter", it's runing well, no error; and "play" button runing well too.
![image](https://user-images.githubusercontent.com/37361895/132628702-0fc17b4f-edce-4b04-aa4e-a05d368f2be6.png)

2. second step: switch to Kode Studio window, click "start debuging" button (HTML5 mod)
![image](https://user-images.githubusercontent.com/37361895/132626364-766a4159-9576-4051-a806-a55d76a338d7.png)
then, I got errors:
![image](https://user-images.githubusercontent.com/37361895/132626517-97430bcd-6e11-4e38-99cc-594b31160578.png)
error txt
```shell
Unable to load preload script: D:\record\armory3d-demo\project\shot\src\build\debug-html5\preload.js
init.js:164
TypeError: Cannot read property 'exposeInMainWorld' of undefined
init.js:165
    at Object.<anonymous> (D:\record\armory3d-demo\project\shot\src\build\debug-html5\preload.js:20:24)
    at Object.<anonymous> (D:\record\armory3d-demo\project\shot\src\build\debug-html5\preload.js:49:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\steamGames\steamapps\common\Kode Studio\resources\electron.asar\renderer\init.js:162:5)
TypeError: Cannot read property 'loadBlob' of undefined
LoaderImpl.hx:216
    at Function.kha_LoaderImpl.loadBlobFromDescription (file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:29599:34)
    at Function.kha_Assets.loadBlobFromPath (file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:28477:17)
    at loadLibAmmo (file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:2037:14)
    at Function.armory_system_Starter.main (file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:2044:2)
    at Function.Main.main (file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:109:24)
    at file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:60769:6
    at file:///D:/record/armory3d-demo/project/shot/src/build/debug-html5/kha.js:60770:3
```

How can I fix this problem?

**Comment by MoritzBrueckner** [comment]
Hi and thanks for the report. This is very likely because of Kode Studio which wasn't updated in a while but Kha and Electron (used for html5 debugging) were updated a lot.

I'm not sure if Rob (the author of Kha and Kode Studio) still plans to continue working on Kode Studio or if it is abandoned, so you probably should use VSCode (or VSCodium without MS telemetry) with the Kha extension pack, with that it should work :)

Please let me know if it works so we can close this issue and update the wiki accordingly.

**Comment by SaxonGao-SZ** [comment]
Tanks for reply and your solution. 
I'll try VSCode with Kha extension. 
And this is not amorySDK's probably,  I‘ close this issues soon.

**Comment by MoritzBrueckner** [comment]
Hi @SaxonGao-SZ, did using VSCode work for you? I'm asking because if the error was indeed caused by Kode Studio we should update the wiki accordingly.

**Comment by SaxonGao-SZ** [comment]
I still using Kode , but vscode is working too(without debuging).



发自我的iPhone


------------------ Original ------------------
From: Moritz Brückner ***@***.***&gt;
Date: Mon,Sep 27,2021 9:21 PM
To: armory3d/armory ***@***.***&gt;
Cc: SaxonGao-SZ ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [armory3d/armory] Can not debugging with Kode studio (#2333)





 
Hi @SaxonGao-SZ, did using VSCode work for you? I'm asking because if the error was indeed caused by Kode Studio we should update the wiki accordingly.
