### ISSUE TITLE
Publishing to Windows Krom gives error

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2343]
**Description**

Building and then publishing to Windows Krom gives the following error. The Krom and data files are generated though.

```
Parse error at E:\blender test\Armory Crash Test\build_Armory Crash Test\krom/krom.js:5,6
class HxOverrides {
      ^
ERROR: Unexpected token: name (HxOverrides)
    at JS_Parse_Error.get (eval at <anonymous> (E:\Armory\ArmorySDK\lib\armory_tools\uglifyjs\tools\node.js:21:1), <anonymous>:75:23)
    at fatal (E:\Armory\ArmorySDK\lib\armory_tools\uglifyjs\bin\uglifyjs:284:53)
    at run (E:\Armory\ArmorySDK\lib\armory_tools\uglifyjs\bin\uglifyjs:228:9)
    at Object.<anonymous> (E:\Armory\ArmorySDK\lib\armory_tools\uglifyjs\bin\uglifyjs:158:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
Exported Krom package to E:\blender test\Armory Crash Test\build_Armory Crash Test\krom-windows
```

**To Reproduce**
Create a new default scene and build and publish for Windows Krom.

**Expected behavior**
The specified error should not occur

**System**
Blender: 2.93
Armory: v2021.9 ($Id: 58e9d91edc6e2519eaa90f5ec9e3c64ce52e6348 $)
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
I can confirm this, however the build folder opens after publishing and I can run the executable. It seems like the error happens in uglify.js so the js can't be minified properly. @luboslenco Do you think this could be related to the switch to ES6? Probably uglify.js just needs to be updated.

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armory_tools/commit/f4478e40f0f2d4d167c4893867b6d8452374e333.

**Comment by MoritzBrueckner** [comment]
Works again, thank you!
