### ISSUE TITLE
debug console exception with multiple cameras in the scene

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#235]
With two cameras in the scene and debug console enabled, when clicking on the screen:

Trace: RangeError: Maximum call stack size exceeded
    at Function.js_Boot.__string_rec (krom.js:15679:32)
    at Function.Std.string (krom.js:272:17)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2733:53)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)
    at Function.armory_trait_internal_DebugConsole.consoleTrace (krom.js:2734:37)

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/armory/commit/2d2197d1ecd8db05104b0153dd667bf60defdb07
