### ISSUE TITLE
AttributeError: 'Object' object has no attribute 'cycles_visibility'

### ISSUE THREAD

**Issue by ManPython** [armory3d/armory#2494]
**Description**

I have error:
```Python: Traceback (most recent call last):
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\props_ui.py", line 1175, in invoke
    return self.execute(context)
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\props_ui.py", line 1196, in execute
    make.play()
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\make.py", line 509, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\make.py", line 429, in build
    export_data(fp, sdk_path)
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\make.py", line 171, in export_data
    ArmoryExporter.export_scene(bpy.context, asset_path, scene=scene, depsgraph=depsgraph)
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\exporter.py", line 169, in export_scene
    cls(context, filepath, scene, depsgraph).execute()
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\exporter.py", line 2352, in execute
    self.export_object(bobject, self.scene)
  File "D:\ArmorySDK2205\armsdk/armory\blender\arm\exporter.py", line 749, in export_object
    if not bobject.cycles_visibility.camera:
AttributeError: 'Object' object has no attribute 'cycles_visibility'

location: <unknown location>:-1

```

**To Reproduce**
I planed test the armory with some advanced scene, eg. splash:
https://cloud.blender.org/p/gallery/5eff317d7920214fcfa0770e

**Expected behavior**
To export .exe and to web

**System**
Blender: blender 3.01 and any upper
Armory: 2022.05.0
OS: W10
Graphics card: gtx

**Test File**
https://cloud.blender.org/p/gallery/5eff317d7920214fcfa0770e

**Comment by QuantumCoderQC** [comment]
Hi, the latest release of Armory only supports Blender 2.9X LTS versions. Hence the error. An experimental repository that supports Blender 3.X LTS can be found [here](https://github.com/armory3d/armory/tree/blender-3.3-lts)

**Comment by ManPython** [comment]
I copied 
https://github.com/armory3d/armory/tree/blender-3.3-lts
to
ArmorySDK2205\armsdk3\armory
and error:
```
Python: Traceback (most recent call last):
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\props_ui.py", line 1054, in invoke
    return self.execute(context)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\props_ui.py", line 1075, in execute
    make.play()
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\make.py", line 509, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\make.py", line 429, in build
    export_data(fp, sdk_path)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\make.py", line 171, in export_data
    ArmoryExporter.export_scene(bpy.context, asset_path, scene=scene, depsgraph=depsgraph)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\exporter.py", line 169, in export_scene
    cls(context, filepath, scene, depsgraph).execute()
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\exporter.py", line 2344, in execute
    self.export_object(bobject, self.scene)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\exporter.py", line 1028, in export_object
    self.post_export_object(bobject, out_object, object_type)
  File "D:\Blender\Add-in\ArmorySDK2205\armsdk3/armory\blender\arm\exporter.py", line 2655, in post_export_object
    self.add_hook_mod(o, bobject, modifier.object.name, modifier.vertex_group)
AttributeError: 'NoneType' object has no attribute 'name'
```

Is this procedure copying is good as replacing? 

I just looking test for big blender enviroment/3dmap, eg. terrain or something to see how this working in browser or it's sense to go in this direction in future.

**Comment by MoritzBrueckner** [comment]
As long as all the different files are correctly overwritten there shouldn't be a difference between copying and replacement.

Have you tested the same file with Blender 2.93? It may be that this error is caused by an unsupported modifier and independent of the Blender version used.
