### ISSUE TITLE
Crash when compiling with UDIM image

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2510]
I followed the steps:
Create picture
Add tiles
Save picture
Replace images with the tileable texture

And when compiling I get:

Error: ENOENT: no such file or directory, rename 'build_Atol/debug/krom/SandDesert1_albedo_UDIM_1001.png.temp' -> 'build_Atol/debug/krom/SandDesert1_albedo_UDIM_1001.png'
    at Object.fs.renameSync (fs.js:766:18)
    at ChildProcess.process.on (/home/yvain/Documents/ArmorySDK2206/armsdk/Kha/Tools/khamake/out/ImageTool.js:54:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by e2002e** [comment]
The issue was that I did not save the main image holding the tiles under the name of the first index _1001
