### ISSUE TITLE
Render Capture not working on Linux

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#259]
Terminal fills up with this error when clicking Render.
```
Traceback (most recent call last):
  File "..removed../Armory/armsdk//armory/blender/arm/handlers.py", line 66, in on_scene_update_post
    import numpy
  File "..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: ..removed../Armory/2.79/python/lib/python3.5/dist-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so: undefined symbol: cblas_cdotc_sub
```

**Comment by luboslenco** [comment]
Working on native capture support in armory+b2.8. Merge with https://github.com/armory3d/armory/issues/608.
