### ISSUE TITLE
@prop has to be on a separate line

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#264]
I just tried to expose some trait properties and stumbled upon this error.

```haxe
class SomeTrait extends armory.Trait {
    @prop public var radius: Int = 4; // see error below

    @prop
    public var radius: Int = 4; // ok
}
```

```shell
Armory v17.09
OS: win, Target: krom, GAPI: opengl
Scene built in 0.019998788833618164
Exported modules: []
Traceback (most recent call last):
  File "e:/dev/armory-b13/armsdk//armory/blender\arm\props_ui.py", line 556, in execute
    make.play_project(True)
  File "e:/dev/armory-b13/armsdk//armory/blender\arm\make.py", line 406, in play_project
    arm.utils.fetch_script_props(fn) # Trait props
  File "e:/dev/armory-b13/armsdk//armory/blender\arm\utils.py", line 178, in fetch_script_props
    p = l.split('var ')[1]
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/armory/commit/ca80d71927eaa98c609a034837c5bf81ca89a4f9
