### ISSUE TITLE
Launching browser player doesn't work in Armory

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armory#2680]
Hi @tong (please excuse the ping). I've been getting these Browser Player related errors for a few months now, which causes the Armory, Browser Player to not launch, even in a new blend.
* Armory Exporter, building for HTML5 work fine.
* I just recently checked again in a clean sdk via the `Update SDK` Git operation - no luck.

```
Traceback (most recent call last):
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\handlers.py", line 143, in poll_threads
    raise e
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\handlers.py", line 136, in poll_threads
    callback()
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\make.py", line 516, in build_done
    build_success()
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\make.py", line 620, in build_success
    state.proc_play = run_proc(cmd, play_done)
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\make.py", line 80, in run_proc
    p = subprocess.Popen(cmd)
  File "D:\Blender\Projects\RP\B3D_33\3.3\python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Blender\Projects\RP\B3D_33\3.3\python\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

If my memory serves well, I first started experiencing these crashes/errors after [this](https://github.com/armory3d/armory/commit/8c63a0b53e907c7d1f49750563e3718a638f835c) commit.

I'm aware Armory users can recently state [custom arguments](https://github.com/armory3d/armory/pull/2605) for the Browser Player. However, I was never able to get them to work. Most likely I'm doing something wrong, but there's also the possibility that errors above are causing the Browser Player to fail in any case.

**Comment by tong** [comment]
Maybe you have set something invalid for $ARMORY_PLAY_HTML5.
Is there any output between 'Finished in 0.s' and this error when building with verbose mode enabled?

**Comment by rpaladin** [comment]
Oof. Apparently I had an environment variable for `ARMORY_PLAY_HTML5` that I entirely forgot about. It was causing the issue (because of errors). 🤦I had entirely forgotten I had created it until you mentioned the possibility. I usually only use `SET`, not `SETX`, and that's why I didn't think of it before.

Sorry for the false report. My mistake entirely. Thanks!
