### ISSUE TITLE
Unsafe use of webbrowser.get() - reported problems with macOS

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#2693]
In https://github.com/armory3d/armory/pull/2602, `webbrowser.open()` was replaced by `webbrowser.get()` + then manually calling the command to open the browser. This causes some issues, since `webbrowser.get()` seems to only return the first browser Python thinks _could_ exist on a system, but the return value doesn't necessarily point to an actually installed browser...

This error message was reported twice this week by macOS users on Discord ([related thread](https://discord.com/channels/486771218599510021/1049194720263417976)):

```
Exporting Scene
Scene exported in 0.002s
Finished in 3.167s
Traceback (most recent call last):
  File "[...]/armsdk/armory/blender/arm/handlers.py", line 143, in poll_threads
    raise e
  File "[...]/armsdk/armory/blender/arm/handlers.py", line 136, in poll_threads
    callback()
  File "[...]/armsdk/armory/blender/arm/make.py", line 517, in build_done
    build_success()
  File "[...]/armsdk/armory/blender/arm/make.py", line 621, in build_success
    state.proc_play = run_proc(cmd, play_done)
  File "[...]/armsdk/armory/blender/arm/make.py", line 80, in run_proc
    p = subprocess.Popen(cmd)
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/subprocess.py", line 966, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'default'
```

If you take a look at the `webbrowser` module, you can see that Python generates a list of potential browsers, `get()` returns the first entry and `open()` [iterates over all of them until one of them works](https://github.com/python/cpython/blob/bed15f87eadc726122185cf41efcdda289f4a7b1/Lib/webbrowser.py#L85-L89). Of course we could implement the same, but `_tryorder` is internal and as such could theoretically change anytime...

The risk of using `_tryorder` is probably rather small, but what do you think about reverting back to `webbrowser.open()` (this time with `new=2`, or simply using `webbrowser.open_new_tab()`) which seems to be the recommended solution, and then allow to **opt-in to use a user-specified path**?

**Comment by MoritzBrueckner** [comment]
Sounds good! I think it makes more sense to put the text input into the preferences (even though it's a bit buried in there) since it's not related to the project but to the user's configuration.

> Also, i think the output to the terminal is kinda off as the verbose flag enables to print the process calls whereby it would make sense to always print these and let the verbose mode enable the output of everything else.
Such issues would be more visible, probably.

Are you referring to [this](https://github.com/armory3d/armory/blob/9bf86872e8fcfb66832c58b85284127d665c1f9e/blender/arm/make.py#L619-L620) and other occurrences of it? If so, I completely agree. We should either always print the command from within `run_proc()` so that it affects every call of this or catch exceptions from `subprocess.Popen` and then add all the necessary info to the original expection before re-raising it.

**Comment by tong** [comment]
Do we have to reraise the exception or is log.warning enough?
https://github.com/tong/armory/blob/e94e77c1f4872180f2d4bf9c8bd7c76d36feb5b9/blender/arm/make.py#L655-L660

 
> Are you referring to [this](https://github.com/armory3d/armory/blob/9bf86872e8fcfb66832c58b85284127d665c1f9e/blender/arm/make.py#L619-L620) 

Exactly.
I think the perfect output in non-verbose mode would allow to re-run the build by executing line by line (even if that's not possible in realtiy) .. extra information only in verbose mode.

**Comment by MoritzBrueckner** [comment]
Assuming that we always print the command before executing it, it should suffice if we catch the exception in this specific case and only output a warning like you did. For other cases there should still be an exception so that we can see a stack trace and the build is aborted. In those cases nothing needs to change apart from printing the command, which should preferably happen from within `run_proc()` so that it doesn't have to be repeated everywhere.
