### ISSUE TITLE
"Pick RB" is broken in 2022.12a

### ISSUE THREAD

**Issue by kmcasi** [armory3d/armory#2714]
**Description**
The example from **armory_examples-master\physics_picking** told me that project was created with version *0.7* and I'm using **2022.12* and some things (I do not remember exactly) are nor converted.

**To Reproduce**
Just open the example project from the GitHub. I clone it today (Dec 18th, 2022), and also I got an error from the **winapi** when I try to edit the scripts to see hoe they work because the scripts works fine, just the note tree is broken.

The error what I get when I try to run the node tree instead of scripts
```python
Armory v2022.12 ($Id: 481e88d78f742a53a9f71a4264446e896768eba3 $)
Saved: 'D:\Portables\blender-3.3.2_LTS\armory_examples-master\physics_picking\build_physics_pick\compiled\Assets\envmaps\env_World.jpg'
 Time: 00:00.41 (Saving: 00:00.01)

Exporting Scene
Scene exported in 0.004s
Finished in 1.201s
DirectInput8 / Pad0 / initialized
Initializing a new default audio device.
Trace: TypeError: Cannot read property 'fromNode' of undefined
    at armory_logicnode_PickObjectNode.get (<anonymous>:1087:21)
    at armory_logicnode_PrintNode.run (<anonymous>:1131:30)
    at armory_logicnode_MergedMouseNode.runOutput (<anonymous>:581:19)
    at armory_logicnode_MergedMouseNode.update (<anonymous>:997:9)
    at update (<anonymous>:8603:28)
    at kha_TimeTask.task (<anonymous>:29001:4)
    at Function.executeTimeTasks (<anonymous>:28884:76)
    at Function.executeFrame (<anonymous>:28834:18)
    at renderCallback (<anonymous>:29651:17)
```

The error when I try to open the script by pressing the "Edit Script" button from blender.
```python
Python: Traceback (most recent call last):
  File "D:\Portables\blender-3.3.2_LTS\AAA_Plugins\armsdk/armory\blender\arm\props_traits.py", line 330, in execute
    arm.utils.open_editor(hx_path)
  File "D:\Portables\blender-3.3.2_LTS\AAA_Plugins\armsdk/armory\blender\arm\utils.py", line 936, in open_editor
    subprocess.Popen(args)
  File "D:\Portables\blender-3.3.2_LTS\3.3\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Portables\blender-3.3.2_LTS\3.3\python\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied
```

**Expected behavior**
Will be nice to work :))

**System**
Blender: 3.3.2 LTS
Armory: 2022.12a
OS: Windows 10 Pro N, 21H2
Graphics card: nVidia GeForce MX230

**Test File**
[*(drag & drop the zipped .blend file here)*](https://github.com/armory3d/armory_examples/tree/master/physics_picking) "was updated last year" they said 😞

**Comment by kmcasi** [comment]
Never mind, problem solved... I got a special delivery what was mist up by the courier. 😄 
![image](https://user-images.githubusercontent.com/58650442/208308070-59ba2cad-0b27-44e9-9dd0-02fa531d51db.png)
