### ISSUE TITLE
Krom target play broken in build 14 rc0

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#278]
**Error in console:**
Traceback (most recent call last):  File "/home/guzzard/bin/Armory/2.79/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner    self.run()  File "/home/guzzard/bin/Armory/2.79/python/lib/python3.5/threading.py", line 1180, in run    self.function(*self.args, **self.kwargs)  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/make.py", line 360, in watch_compile    on_compiled(mode)  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/make.py", line 482, in on_compiled    os.chdir(krom_location)FileNotFoundError: [Errno 2] No such file or directory: '/home/guzzard/bin/Armory/armsdk//linux64/resources/app/extensions/krom/Krom/linux'

**Comment by luboslenco** [comment]
I think this is because of the symlinks not being placed in the b14 archive.

Can you try to move/symlink `Armory/armsdk/linux64/Krom` to `Armory/armsdk/linux64/resources/app/extensions/krom/Krom`?

Next release will come pre-set like this.

**Comment by guzzard** [comment]
@luboslenco yes, working after adding a symlink, thanks!
