### ISSUE TITLE
Error when opening file with linked proxy objects in build 14 rc0

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#279]
**Error in console:**
Traceback (most recent call last):  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/handlers.py", line 231, in on_load_post    bpy.ops.arm.sync_proxy()  File "/home/guzzard/bin/Armory/2.79/scripts/modules/bpy/ops.py", line 189, in _call_    ret = op_call(self.idname_py(), None, kw)RuntimeError: Error: Traceback (most recent call last):  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/props_ui.py", line 1328, in execute    arm.proxy.sync_location(obj)  File "/home/guzzard/bin/Armory/armsdk//armory/blender/arm/proxy.py", line 35, in sync_location    obj.location = obj.proxy.locationAttributeError: 'NoneType' object has no attribute 'location'location: /home/guzzard/bin/Armory/2.79/scripts/modules/bpy/ops.py:189

**Comment by luboslenco** [comment]
Should be now fixed in https://github.com/armory3d/armory/commit/d56be0e8f218a731e5b7f1386841e4259057b20f.

**Comment by guzzard** [comment]
Can confirm that it's fixed, thanks!
