### ISSUE TITLE
problems running some html examples

### ISSUE THREAD

**Issue by stellanhaglund** [armory3d/armory#293]
if I for example try the html access example and choose browser I get.

```
fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'build_html/html5-resources/Material_mesh.vert.essl.temp' -> 'build_html/html5-resources/Material_mesh.vert.essl'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at ChildProcess.child.on (blender.app/armsdk/Kode Studio.app/Contents/Resources/app/extensions/kha/Kha/Tools/khamake/out/ShaderCompiler.js:356:48)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

```

**Comment by stellanhaglund** [comment]
Sorry  I just needed the newer version of the examples.
