### ISSUE TITLE
Unable to view armory in Blender 4.1

### ISSUE THREAD

**Issue by Leonalx87** [armory3d/armory#3040]
Not sure if this is the right place to ask for support but I am not able to use Armory3d in Blender 4.1. It is the error message because armory is for blender 3.6 or I am missing something and it could be fixed?

Thank you!

Read prefs: "C:\Users\leona\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Error in bpy.app.handlers.load_post[1]:
Traceback (most recent call last):
  File "C:\Users\leona\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\armory.py", line 919, in on_load_post
    restart_armory(bpy.context)  # context is None, use bpy.context instead
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\armory.py", line 914, in restart_armory
    start_armory(sdk_path)
  File "C:\Users\leona\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\armory.py", line 872, in start_armory
    import start
  File "C:\Program Files\armsdk/armory\blender\start.py", line 5, in <module>
    import arm.nodes_logic
  File "C:\Program Files\armsdk/armory\blender\arm\nodes_logic.py", line 9, in <module>
    import arm.logicnode.arm_nodes as arm_nodes
  File "C:\Program Files\armsdk/armory\blender\arm\logicnode\__init__.py", line 7, in <module>
    import arm.logicnode.arm_nodes as arm_nodes
  File "C:\Program Files\armsdk/armory\blender\arm\logicnode\arm_nodes.py", line 10, in <module>
    from arm.logicnode.arm_sockets import ArmCustomSocket
  File "C:\Program Files\armsdk/armory\blender\arm\logicnode\arm_sockets.py", line 598, in <module>
    def _make_socket_interface(interface_name: str, bl_idname: str) -> Type[bpy.types.NodeSocketInterface]:
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Onek8** [comment]
Are you using the github repo?
This is the line that should fix the error for you
-> https://github.com/armory3d/armory/pull/3028/commits/277d5dde39c09e1955381c32c97a1cbd731ebdc4#diff-09b543c772604fb625ee9049f3dda3d1ef609c4415db15547946e3c3568780c4R598
