### ISSUE TITLE
Preview 02 Linux version crash when trying to run

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#33]
I have made a simple scene of a quad and a point light and I'm trying to run it in armory, but when I press the "Play" on the properties tab or press "P" in viewport, the Armory crashes and outputs this:
```
Traceback (most recent call last):
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/props_ui.py", line 520, in execute
    make.play_project(self, False)
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/make.py", line 307, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/make.py", line 253, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/make.py", line 69, in export_data
    exporter.execute(bpy.context, asset_path)
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/exporter.py", line 2275, in execute
    self.export_materials()
  File "/home/adriansnetlis/Armory3D/Armory//armsdk//armory/blender/exporter.py", line 2088, in export_materials
    c['name'] = ArmoryExporter.mesh_context
AttributeError: type object 'ArmoryExporter' has no attribute 'mesh_context'

location: <unknown location>:-1

```
What's caussing this issue?

**Comment by luboslenco** [comment]
Hi,

This error used to happen when there is no camera placed in the scene. It should now be fixed and show "No camera found in scene." alert when that happens.
