### ISSUE TITLE
Examples files not working except scene1

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#34]
All the Armory Example files, at the exception ok scene1 gives me the following error when I try to run them.

Traceback (most recent call last):
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\props_ui.py", line 543, in execute
    make.play_project(self, True)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make.py", line 307, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make.py", line 253, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make.py", line 69, in export_data
    exporter.execute(bpy.context, asset_path)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\exporter.py", line 2275, in execute
    self.export_materials()
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\exporter.py", line 2079, in export_materials
    self.post_export_material(material, o)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\exporter.py", line 2667, in post_export_material
    make_material.parse(self, material, c, defs)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 22, in parse
    parse_from(self, material, c, defs, surface_node)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 104, in parse_from
    parse_material_surface(self, material, c, defs, tree, surface_node, 1.0)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 217, in parse_material_surface
    parse_pbr_group(self, material, c, defs, tree, node, factor)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 509, in parse_pbr_group
    parse_base_color_socket(self, base_color_input, material, c, defs, tree, node, factor)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 430, in parse_base_color_socket
    add_albedo_tex(self, color_node, material, c, defs)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 367, in add_albedo_tex
    tex = make_texture(self, 'sbase', node, material)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\make_material.py", line 115, in make_texture
    tex['file'] = armutils.extract_filename(image.filepath)
  File "E:\Armory\Armory_p02_win32\Armory\armsdk\/armory/blender\armutils.py", line 105, in extract_filename
    return s.rsplit(os.path.sep, 1)[1]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Will fix - thanks for report! As you see, the preview is still super dumb:)

**Comment by JeannotLandry** [comment]
Its a work in progress man ;) A great awesome work in progress :)

**Comment by luboslenco** [comment]
Fixed in Build 3!

**Comment by JeannotLandry** [comment]
They all work but the grease pencil! The animation skips for some reasons, I only see one frame, the rest is a blur. So all the other files work but the grease pencil.

**Comment by luboslenco** [comment]
The animation has to be played first in Blender viewport, there is some caching Blender does, still have to look into that.

**Comment by JeannotLandry** [comment]
It is working in the viewport!

**Comment by JeannotLandry** [comment]
just not when I hit play
