### ISSUE TITLE
Adding an armature causes crash

### ISSUE THREAD

**Issue by songproducer** [armory3d/armory#35]
```
Traceback (most recent call last):
  File "/Applications/Armory//armsdk//armory/blender/props_ui.py", line 520, in execute
    make.play_project(self, False)
  File "/Applications/Armory//armsdk//armory/blender/make.py", line 307, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "/Applications/Armory//armsdk//armory/blender/make.py", line 253, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/Applications/Armory//armsdk//armory/blender/make.py", line 69, in export_data
    exporter.execute(bpy.context, asset_path)
  File "/Applications/Armory//armsdk//armory/blender/exporter.py", line 2265, in execute
    self.export_object(object, self.scene)
  File "/Applications/Armory//armsdk//armory/blender/exporter.py", line 1339, in export_object
    action = bobject.animation_data.action
AttributeError: 'NoneType' object has no attribute 'action'
```

**Comment by luboslenco** [comment]
Hi,

If not private, is it possible to share the blend file containing the armature? You can also send me the link privately if you wish. That would make it much easier to track.

**Comment by songproducer** [comment]
I am using [Manuel Bastioni's addon](http://www.manuelbastioni.com/download.php), but the same error happens when adding a single empty armature.

**Comment by luboslenco** [comment]
Empty armatures should no longer crash, will be up in next build.

**Comment by songproducer** [comment]
Awesome thanks!
