### ISSUE TITLE
Fix Play in viewport + git Kha

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#405]
Krom and browser works fine but play in viewport fails with this error:

```
Trace: TypeError: Krom.generateTextureMipmaps is not a function
    at $hxClasses.kha.Image.generateMipmaps (krom.js:15943:9)
    at krom.js:9242:13
    at krom.js:3323:4
    at Function.kha_LoaderImpl.loadImageFromDescription (krom.js:16195:2)
    at Function.iron_data_Data.getImage (krom.js:3310:17)
    at $hxClasses.iron.data.MaterialContext [as __class__] (krom.js:9213:19)
    at krom.js:9148:4
    at krom.js:3067:4
    at krom.js:9675:6
    at $hxClasses.iron.data.ShaderContext.finishCompile (krom.js:9887:3)
```
![image](https://user-images.githubusercontent.com/9007314/33718173-cf66716e-db5c-11e7-92e3-9bcf9bfd3395.png)

If I break the connection to the image texture it plays fine in viewport as well.

**Comment by luboslenco** [comment]
Is this with latest git Kha or bundled Kha?

**Comment by guzzard** [comment]
Updated git :grin: ..bundled Kha workes fine :+1: ..closing!

**Comment by luboslenco** [comment]
Hehe, have to fix this anyway so it works perfectly with git Kha too:). The reason for error - need to update Blender build to use the latest git Kore/Krom.

**Comment by luboslenco** [comment]
Should be fine now.
