### ISSUE TITLE
haunted objects cause black screen

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#471]
I wanted to make [this](https://www.blendswap.com/blends/view/41683) scene viewable in Armory, so I did some stuff with the materials, removed SubSurfaces and fixed normals, and everything was working wonderfully until I accidentally closed Blender while the F5 preview was running.
Now when I press F5 the screen is black, not even the debug console shows up.
So I tried cleaning the project, redownloading and updating Armory (that worked once), moving all objects into a new .blend, but nothing helped and sometimes I get this error message:
`Exporting mesh Plane.092
Exporting mesh Plane.078
Exporting mesh Plane.089
Exporting mesh Plane.054
Exporting mesh Plane.033
Traceback (most recent call last):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\props_ui.py", line 561, in execute
    make.play_project(False)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 436, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 344, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 113, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene, write_capture_info=state.is_render_anim, play_area=state.play_area)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 2070, in execute
    self.export_objects(self.scene)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1910, in export_objects
    self.export_mesh(objectRef, scene)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1374, in export_mesh
    if not self.mod_equal_stack(bobject, table[i]):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 2631, in mod_equal_stack
    return all([self.mod_equal(m, obj2.modifiers[i]) for i,m in enumerate(obj1.modifiers)])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 2631, in <listcomp>
    return all([self.mod_equal(m, obj2.modifiers[i]) for i,m in enumerate(obj1.modifiers)])
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

location: <unknown location>:-1
`

[hauntedobjects.zip](https://github.com/armory3d/armory/files/1669948/hauntedobjects.zip)

Help please! It took quite some time to get it to the point at which it was looking good before breaking.

**Comment by luboslenco** [comment]
Uh, haunted objects triggered a bug, now fixed in https://github.com/armory3d/armory/commit/0fe2d17fccbf9f29cc51013e3c8b262b9ad6df1a.
