### ISSUE TITLE
Unable to run 'Play in Viewport' in Armory .2

### ISSUE THREAD

**Issue by jrdoughty** [armory3d/armory#489]
I got this when I tried to click the Play in Viewport. I was using the build in the zip: Armory02_win64

```
Read prefs: C:\Users\johnd\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Users\johnd\Downloads\Armory\2.79\python
Read blend: C:\Users\johnd\Documents\Projects\test.blend
Project updated to sdk v0.2.0
Project cleaned

Armory v0.2.0 ($Id: bebbb7fa00e259ed7a026970637a60b0abab7b52 $)


OS: win, Target: krom, GAPI: opengl
Exporting Scene
Exporting mesh Cube
Scene built in 0.026502609252929688
Exported modules: []
Shader flags: ['_Irr', '_EnvCol', '_CSM', '_SMAA', '_SSAO']
Running:  ['C:/Users/johnd/Downloads/Armory/armsdk//nodejs/node.exe', 'Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_test']
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\johnd\Documents\Projects\Kha\Kore\Tools\kraffiti\kraffiti.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Finished in 0.6822793483734131
Build failed, check console
```

**Comment by luboslenco** [comment]
Hi! Looks like Armory tries to pick up your local Kha placed alongside the .blend file at `C:\Users\johnd\Documents\Projects\Kha`, instead of the bundled one at `C:\Users\johnd\Downloads\Armory\armsdk\Kha`.

Is this local Kha complete? Alternatively, try moving the blend file to a subfolder.

**Comment by jrdoughty** [comment]
Doh! Yup, I had a version of Kha just sitting in my projects folder. Nixed that and go figure, it runs!

**Comment by jrdoughty** [comment]
Thanks for the help Lubos! I can't wait to get started!
