### ISSUE TITLE
Armory 0.2 Kode Studio won't lanuch on mac

### ISSUE THREAD

**Issue by brooksandy** [armory3d/armory#492]
mac (OS 10.12.5) using Armory v0.2. get the following error message:

https://dl.dropboxusercontent.com/s/pya899hsa3xqf8q/Armoury%20error.png?dl=0

**Comment by luboslenco** [comment]
Reorganized sdk structure for v0.2 and this slipped in.:( Fixed it in git.

It should be still possible to launch Kode Studio on macOS + v0.2 from traits panel by clicking `Edit Script`:
![capture](https://user-images.githubusercontent.com/3685704/36277257-aa9500ec-1290-11e8-964d-4f49582e937c.PNG)

**Comment by boringuser** [comment]
Experiencing same issue, Mac OS 10.12.6, Armory 0.2. Followed the instructions [here](http://armory3d.org/manual/dev/gitversion.html) to use latest from git, but still see this error after pressing Edit Script:

```
Traceback (most recent call last):
  File "/private/var/folders/sk/rqvybn5j36v7_zqd_l_4p81m0000gn/T/AppTranslocation/36502367-A2F8-4185-8DB9-715863FDD1CA/d/blender.app//armsdk//armory/blender/arm/props_traits.py", line 251, in execute
    arm.utils.kode_studio_mklink_mac(sdk_path)
  File "/private/var/folders/sk/rqvybn5j36v7_zqd_l_4p81m0000gn/T/AppTranslocation/36502367-A2F8-4185-8DB9-715863FDD1CA/d/blender.app//armsdk//armory/blender/arm/utils.py", line 471, in kode_studio_mklink_mac
    subprocess.check_call('ln -s "%s" "%s"' % (target, source), shell=True)
  File "/private/var/folders/sk/rqvybn5j36v7_zqd_l_4p81m0000gn/T/AppTranslocation/36502367-A2F8-4185-8DB9-715863FDD1CA/d/blender.app/Contents/Resources/2.79/python/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ln -s "/private/var/folders/sk/rqvybn5j36v7_zqd_l_4p81m0000gn/T/AppTranslocation/36502367-A2F8-4185-8DB9-715863FDD1CA/d/blender.app//armsdk//Kha" "/private/var/folders/sk/rqvybn5j36v7_zqd_l_4p81m0000gn/T/AppTranslocation/36502367-A2F8-4185-8DB9-715863FDD1CA/d/blender.app//armsdk//Kode Studio.app/Contents/Resources/app/extensions/kha/Kha"' returned non-zero exit status 1

location: <unknown location>:-1
```

**Comment by anadin** [comment]
I've made a pull request that deals with this hope its OK (my 1st ever PR)

https://github.com/armory3d/armory/pull/525
