### ISSUE TITLE
Drawing shadowmap cascades slow

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#562]
I am getting about double the fps in this .blend in 0.2 compared to 0.3, while 0.2 has VXGI turned on and 0.3 don't.
https://drive.google.com/open?id=1u3h6OSmYe-me7wVMPqK-D1AkQTdZ2S4j

**Comment by Simonrazer** [comment]
Oups the first link was wrong

**Comment by luboslenco** [comment]
Trying to reproduce but no luck so far. One strange thing is that you compare with different settings, even though clearly vxgi should be the slower one here. Are there any other differences? Can you try to test both using the `Deferred` preset?

On my machine 0.3 appears the same and I get further 5-10% speedup using the Direct3D11 Krom player, which will be selectable in the final 0.3 build on Windows. Hopefully we can get those numbers on not-my-own machines as well!

**Comment by Simonrazer** [comment]
Sorry for not using the same settings, should have done that.
Now I can't even get 0.3 to launch the file anymore, it gives me this console error. The same file works in 0.2 just fine, in which I get now on Deferred settings also 30 fps? Yes tested it and only turning VXGI on in V0.2 gives me more fps (60). In V0.3 I had about 30 also with deferred preset and the only thing I changed I hope was the shadow map res to 2048 from 1024.

```
Armory Warning: No camera found in active scene
Armory Warning: Material Material__25/lion_ddn.tga - file not found(C:\Users\SK\Desktop\Armory\blends\sponanza\build_spa\compiled\Assets\unpacked\lion_ddn.jpg)
Armory Info: Writing C:\Users\SK\Documents\GitHub\Sponza/build_spa/compiled/Assets/unpacked/lion.jpg
Traceback (most recent call last):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\props_ui.py", line 546, in execute
    make.play_project(False)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 447, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 355, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 117, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene, write_capture_info=state.is_render_anim, play_area=state.play_area)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 2088, in execute
    self.export_materials()
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1796, in export_materials
    sd, rpasses = make_material.parse(material, o, mat_users, mat_armusers)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make.py", line 48, in parse
    rpasses, shader_data, shader_data_name, bind_constants, bind_textures = make_shader.build(material, mat_users, mat_armusers)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_shader.py", line 83, in build
    con = make_transluc.make(rp)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_transluc.py", line 10, in make
    make_mesh.make_forward_base(con_transluc, parse_opacity=True)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_mesh.py", line 538, in make_forward_base
    make_base(con_mesh, parse_opacity=(parse_opacity or arm_discard))
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_mesh.py", line 167, in make_base
    cycles.parse(mat_state.nodes, con_mesh, vert, frag, geom, tesc, tese, parse_opacity=parse_opacity)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 34, in parse
    parse_output(output_node, con, vert, frag, geom, tesc, tese, parse_surface, parse_opacity, parse_displacement, basecol_only)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 90, in parse_output
    out_basecol, out_roughness, out_metallic, out_occlusion, out_opacity = parse_shader_input(node.inputs[0])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 151, in parse_shader_input
    return parse_shader(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 235, in parse_shader
    bc1, rough1, met1, occ1, opac1 = parse_shader_input(node.inputs[0])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 151, in parse_shader_input
    return parse_shader(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 235, in parse_shader
    bc1, rough1, met1, occ1, opac1 = parse_shader_input(node.inputs[0])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 151, in parse_shader_input
    return parse_shader(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 223, in parse_shader
    bc2, rough2, met2, occ2, opac2 = parse_shader_input(node.inputs[2])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 151, in parse_shader_input
    return parse_shader(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 273, in parse_shader
    out_basecol = parse_vector_input(node.inputs[0])
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 430, in parse_vector_input
    res_var = write_result(l)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 388, in write_result
    res = parse_rgb(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 623, in parse_rgb
    col2 = parse_vector_input(node.inputs[2], vec_size=3)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 430, in parse_vector_input
    res_var = write_result(l)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 388, in write_result
    res = parse_rgb(l.from_node, l.from_socket)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 511, in parse_rgb
    tex = make_texture(node, tex_name)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\cycles.py", line 1374, in make_texture
    return arm.material.make_texture.make(node, name)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_texture.py", line 81, in make
    arm.utils.write_image(image, converted_path)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\utils.py", line 32, in write_image
    image.save()
RuntimeError: Error: Image 'lion.tga' does not have any image data


location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by luboslenco** [comment]
Improved in 0.4.
