### ISSUE TITLE
Material batch fails on v0.3

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#566]
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Armory Warning: No camera found in active scene
Traceback (most recent call last):
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\props_ui.py", line 546, in execute
    make.play_project(False)
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\make.py", line 447, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\make.py", line 355, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\make.py", line 117, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene, write_capture_info=state.is_render_anim, play_area=state.play_area)
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 2090, in execute
    self.export_materials()
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\exporter.py", line 1758, in export_materials
    mat_batch.build(self.materialArray, mat_users, mat_armusers)
  File "E:/GAMES/Armory02_win64/Armory/armsdk//armory/blender\arm\material\mat_batch.py", line 100, in build
    for ref in materialArray.items():
AttributeError: 'list' object has no attribute 'items'

Scene > https://github.com/Simonrazer/Sponza

**Comment by trsh** [comment]
@luboslenco how about this for v4.0? Seems like a very important thing to lower draw calls.

**Comment by luboslenco** [comment]
Should no longer error out now.
