### ISSUE TITLE
Forward rendering broken

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#568]
I get this error when trying to F5 a project with Forward rendering, it is working for other people and I am using the latest version:
```
Armory v0.3.0 ($Id: 779f2b146b510055bb5510bcd4638bc9d3f20757 $)
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Armory Warning: No camera found in active scene
Traceback (most recent call last):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\props_ui.py", line 546, in execute
    make.play_project(False)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 447, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 355, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 117, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene, write_capture_info=state.is_render_anim, play_area=state.play_area)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 2089, in execute
    self.export_materials()
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1797, in export_materials
    sd, rpasses = make_material.parse(material, o, mat_users, mat_armusers)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make.py", line 48, in parse
    rpasses, shader_data, shader_data_name, bind_constants, bind_textures = make_shader.build(material, mat_users, mat_armusers)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_shader.py", line 74, in build
    con = make_mesh.make(rp)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_mesh.py", line 44, in make
    make_forward(con_mesh)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_mesh.py", line 515, in make_forward
    make_forward_base(con_mesh)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\material\make_mesh.py", line 548, in make_forward_base
    frag.main_pre += """
AttributeError: 'Shader' object has no attribute 'main_pre'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by luboslenco** [comment]
It's back, also fixed vxgi intensity in forward to match deferred. (https://github.com/armory3d/armory/commit/77685755c9b7d8c65d20b794ad56df6ba0cdde57, https://github.com/armory3d/armory/commit/09db2a4d013ac895e38b33b3b162989f6b1e252e)
