### ISSUE TITLE
player not starting on osx

### ISSUE THREAD

**Issue by stellanhaglund** [armory3d/armory#582]
Hi I tried running a scene with just an imported fbx, then I added some emissive planes from another scene and tried again and I get this even if I remove everything but the imported fbx

```
Trace: TypeError: Cannot read property 'length' of null
    at $hxClasses.iron.data.Geometry.build (krom.js:8719:9)
    at $hxClasses.iron.object.MeshObject.setData (krom.js:12016:14)
    at $hxClasses.iron.object.MeshObject [as __class__] (krom.js:12005:7)
    at $hxClasses.iron.Scene.addMeshObject (krom.js:3767:16)
    at krom.js:4060:24
    at krom.js:2528:4
    at krom.js:9273:4
    at $hxClasses.iron.data.MeshData [as __class__] (krom.js:9246:2)
    at krom.js:9260:3
    at Function.iron_data_Data.returnSceneRaw (krom.js:2871:3)
```

**Comment by luboslenco** [comment]
Hi, any chance to have a look at the `.blend` file so I can reproduce? Is there a difference after doing `Armory Project - Clean`?

**Comment by stellanhaglund** [comment]
No there is no difference, I will see if I saved the blend file.
Could it be an issue in that I append objects from another scene?

**Comment by luboslenco** [comment]
Appending objects should not cause issues. If the bug still persists in 0.4 please let me know.
