### ISSUE TITLE
Kode Studio - Krom debug fails

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory#616]
Though this file can be run with no problem via the viewport or standalone play options in Blender, when using Kode's debug section the game will not run in either target.

[kodeDebugErrors.zip](https://github.com/armory3d/armory/files/1955138/kodeDebugErrors.zip)

When attempting to run the Krom debug section from within Kode. I get the following output in the console. (After the `Discovering targets via http://127.0.0.1:14812/json` the game window appears for a split second then disappears.)

```
Using Kha from C:\Users\USERNAME\Progs\blender\Armory03\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
c:\dev\armory3d\testBug\build\temp\Material_mesh.frag.hlsl(45,72-83): error X3004: undeclared identifier 'gl_FragCoord'

Compiling shader 1 of 1 (Material_mesh.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-text.vert.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Discovering targets via http://127.0.0.1:14812/json
Invalid JSON from target: (Unexpected token 
 in JSON at position 149): {"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"log","text":"Trace: TypeError: Cannot read property 'bytes' of undefined
    at $hxClasses.kha.graphics4.FragmentShader [as __class__] (krom.js:31000:53)
    at Function.kha_Shaders.init (krom.js:18488:35)
    at Function.kha_SystemImpl.init (krom.js:18906:14)
    at Function.kha_System.init (krom.js:18666:17)
    at Function.Main.start (krom.js:220:13)
    at Function.Main.main (krom.js:179:7)
    at krom.js:35111:6","timestamp":0}}}
Error handling message from target: Unexpected token 
 in JSON at position 149
Websocket closed
Terminated: websocket closed
Terminated: Got disconnect request
```

Hitting the green arrow with HTML5 debug, Kode reports 

> Build errors have been detected during preLaunchTask 'Build for Debug HTML5'.

 and the console gives the following output:
```
Using Kha from C:\Users\USERNAME\Progs\blender\Armory03\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\Users\USERNAME\Progs\blender\Armory03\armsdk\iron\Sources/iron/RenderPath.hx:698: characters 20-32 : kha.Image has no field texture_
C:\Users\USERNAME\Progs\blender\Armory03\armsdk\iron\Sources/iron/data/MaterialData.hx:133: characters 10-24 : kha.Image has no field texture_
C:\Users\USERNAME\Progs\blender\Armory03\armsdk\iron\Sources/iron/RenderPath.hx:205: characters 6-23 : kha.Image has no field texture_
C:\Users\USERNAME\Progs\blender\Armory03\armsdk\Kha\Sources/kha/input/Pen.hx:10: characters 9-26 : Class<kha.SystemImpl> has no field getPen

Done.
```
And Kode reports the following issues:
![kode studio_2018-04-27_08-38-40](https://user-images.githubusercontent.com/1477787/39363205-785ec06a-49f7-11e8-8fc4-6a00bd6233a6.png)

**Comment by donalffons** [comment]
I think I may just have coincidentally stumbled across the solution for this. I just started watching [this video (at 2:00 min)](https://youtu.be/Yj11-ybVABA?t=2m) from Robert, the main developer of kha. He explains how to configure the settings "kha.khaPath" and "krom.kromPath". I just pointed them to <yourpath>/Armory/armsdk/Kha and <yourpath>/Armory/armsdk/Krom and now everything works fine.

Does this also work for you?

**Comment by Gerkinfeltser** [comment]
Unfortunately I cannot tell as the original computer I was running into problems on no longer exists. Using the file on a new computer has different problems.

**Comment by Mishurin** [comment]
Hi all,

I met the same issue on ubuntu 16.04. However i have different errors in debug console of Kode:
Graphics.hx:131: WebGL error: Invalid enum.

It happens when I run debug config with F5. For some reason it has HTML5 set by default. From official website video tutorials it should work with HTML5 having Krome as a build target which looks strange to me. I thought HTML5 and Krome are mixed. Krome debug console shows another errors:
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl) failed:
Shader compiler error.

Tried to use paths similar to what blender got when I configured user settings of armory ad-don. But it didn't work.

**Comment by Gerkinfeltser** [comment]
Hmmm, I take it back. This is still an issue for me.

I've attempted adding in the kha & krom paths as @donalffons suggests but no joy.
Perhaps I'm doing it wrong but this is how I added them to Kode's settings curly bracketed:
`"kha.khaPath": "C:\\PATHTOBlender\\Armory0.3\\armsdk\\Kha",`
`"krom.kromPath": "C:\\PATHTOBlender\\Armory0.3\\armsdk\\Krom\\win32"`

When I first hit the green debug triangle, Kode says:
![kode studio_2018-06-26_12-18-31](https://user-images.githubusercontent.com/1477787/41925864-c7a7eed0-793b-11e8-8c0c-d9a07b78ef8e.png)

After hitting "Debug Anyway" the following window appears (hitting "Show Problems" doesn't report any problems either):
![2018-06-26_12-25-36](https://user-images.githubusercontent.com/1477787/41925987-0b929cda-793c-11e8-8fc5-1e49e3ae8079.png)


Using Krom, I don't get the above preLaunchTask Error bar but the output in the console is the same concerning Material_mesh.frag.hlsl though the "Invalid JSON from target" stuff from my orginal post is replaced with a new krom error due to updated krom paths I assume.

```
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
c:\PATHTOBlend\build\temp\Material_mesh.frag.hlsl(49,72-83): error X3004: undeclared identifier 'gl_FragCoord'

Compiling shader 1 of 1 (Material_mesh.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Discovering targets via http://127.0.0.1:15305/json
Krom error: Error: spawn C:\PATHTOBlender\Armory0.3\armsdk\Krom\win32\win32\Krom.exe ENOENT
Terminated: Krom error: Error: spawn C:\PATHTOBlender\Armory0.3\armsdk\Krom\win32\win32\Krom.exe ENOENT
Terminated: Got disconnect request
```

**Comment by luboslenco** [comment]
Linking to https://github.com/armory3d/armory/issues/745.
