### ISSUE TITLE
Errors when starting blender for Armory_04_linux64_b27

### ISSUE THREAD

**Issue by skylerparr** [armory3d/armory#703]
When opening blender from the command line, I get the following error:
```
➜  Armory ./blender
Read prefs: /home/skyler/.config/blender/2.79/config/userpref.blend
found bundled python: /home/skyler/Downloads/Armory/2.79/python
Traceback (most recent call last):
  File "/home/skyler/.config/blender/2.79/scripts/addons/armory.py", line 182, in execute
    import start
  File "/home/skyler/.config/blender/2.79/scripts/addons/start.py", line 13, in <module>
    import arm.space_armory
ImportError: No module named 'arm.space_armory'

location: /home/skyler/Downloads/Armory/2.79/scripts/modules/bpy/ops.py:189
```

I also don't see /Armory/2.79/scripts/modules/bpy in the zipped package. Do I need it?

**Comment by luboslenco** [comment]
I think you may have old armory add-on installed at `/home/skyler/.config/blender/2.79/scripts/addons/armory.py`? Anything suspicious if you look into the add-on preferences in Blender?
