### ISSUE TITLE
WASM (WebAssembly) Call from Haxe fails [Solved]

### ISSUE THREAD

**Issue by thesupremeliverwurst** [armory3d/armory#769]
So here's my bug report, if you're new to this see [here](http://forums.armory3d.org/t/aargh-wasm-doesnt-work).
I uploaded my blend project for reference.
[maybeabug.zip](https://github.com/armory3d/armory/files/2190598/maybeabug.zip)

You will note a variety of wasm files under Bundled (because that's where they go, apparently), which are reminiscent of all of my recompiles at webassembly.studio. In essence, I am trying to call the webassembly from haxe, but it doesn't let me. [My c file](https://pastebin.com/50Xt5Aha) should work, too, but maybe I'm deluded (hopefully). (No error on gcc). Anyways, this is probably an issue, but maybe I'm wrong. Thanks to anyone who responds.

**Comment by thesupremeliverwurst** [comment]
After updating the Armory SDK, the error message changed from
`Error: Trait 'armory.trait.internal.WasmScript' referenced in object 'Suzanne' not found`
to
```
Trace: TypeError: _gthis.wasm.exports.main is not a function
    at krom.js:893:23
    at kha_Assets.loadBlobFromPath.fileName (krom.js:6544:4)
    at Function.kha_LoaderImpl.loadBlobFromDescription (krom.js:16164:2)
    at Function.kha_Assets.loadBlobFromPath (krom.js:15305:17)
    at Function.iron_data_Data.getBlob (krom.js:6531:13)
    at new $hxClasses.armory.trait.internal.WasmScript (krom.js:891:17)
    at Function.Type.createInstance (krom.js:339:10)
    at Function.iron_Scene.createTraitClassInstance (krom.js:5193:14)
    at Function.iron_Scene.createTraits (krom.js:5120:31)
    at $hxClasses.iron.Scene.returnObjectLoaded (krom.js:5789:15)
```
It would appear that normal wasm still works. (I.e. wasm not being called from Haxe but in response to the game logic)

**Comment by thesupremeliverwurst** [comment]
Well, sorry about that. Apparently the wasm file needs a main(). Perhaps that should be added to the armory docs... At any rate, the wasm works well if you add a main with only return 0 in it.

**Comment by luboslenco** [comment]
Added a notice at https://github.com/armory3d/armory_docs/commit/8a5bc86d66cd18ec1d29584e1d6842dd19a1c823. Thanks for mentioning that and sorry for trouble!
