### ISSUE TITLE
ShaderNodeBump object has no attribute 'image'

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#89]
The following results when you try to plug an image into the height parameter of the Bump node:

```
Traceback (most recent call last):
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/props_ui.py", line 454, in execute
    make.play_project(self, False)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make.py", line 310, in play_project
    build_project(is_play=True, in_viewport=in_viewport)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make.py", line 256, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make.py", line 69, in export_data
    exporter.execute(bpy.context, asset_path)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/exporter.py", line 2295, in execute
    self.export_materials()
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/exporter.py", line 2099, in export_materials
    self.post_export_material(material, o)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/exporter.py", line 2694, in post_export_material
    make_material.parse(self, material, c, defs)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 25, in parse
    parse_from(self, material, c, defs, surface_node)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 107, in parse_from
    parse_material_surface(self, material, c, defs, tree, surface_node, 1.0)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 220, in parse_material_surface
    parse_pbr_group(self, material, c, defs, tree, node, factor)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 559, in parse_pbr_group
    parse_normal_map_socket(self, normal_map_input, material, c, defs, tree, node, factor)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 507, in parse_normal_map_socket
    add_normal_tex(self, normal_node, material, c, defs)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 418, in add_normal_tex
    tex = make_texture(self, 'snormal', node, material)
  File "/home/zauber/Armory/Armory_pre03/armsdk//armory/blender/make_material.py", line 113, in make_texture
    image = image_node.image
AttributeError: 'ShaderNodeBump' object has no attribute 'image'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by zauberparacelsus** [comment]
Actually, this error is thrown if the Bump node is used at all

**Comment by luboslenco** [comment]
Placing Bump node should not cause any errors now. Normal Map + normal texture setup is still preferred for now.
